import {validateHostChange} from "@/lib/host-change";
import {getChatGPTUser} from "@/app/chatgpt-auth";
import {database} from "@/db/store";
import {defaults,schemas,settingsSchema, type Kind} from "@/lib/daywell";
import {sameOrigin} from "@/lib/request-guards";
// A generous ceiling per person, so one account can't grow without limit. Edits to existing entries always fit.
const MAX_ENTRIES=20000;
const FULL="Your saved space is full. Remove a few older entries, then try again.";
async function hasRoom(db:ReturnType<typeof database>,userId:string,ids:string[]){if(!ids.length)return true;const existing=await db.prepare(`SELECT id FROM entries WHERE user_id=? AND id IN (${ids.map(()=>"?").join(",")})`).bind(userId,...ids).all<{id:string}>();const fresh=ids.length-existing.results.length;if(!fresh)return true;const row=await db.prepare("SELECT COUNT(*) AS n FROM entries WHERE user_id=?").bind(userId).first<{n:number}>();return (row?.n??0)+fresh<=MAX_ENTRIES;}
export const dynamic="force-dynamic";
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{"Cache-Control":"no-store"}});
export async function GET(){const user=await getChatGPTUser();if(!user)return json({error:"Sign in to save your day."},401);try{const db=database();const [prefs,rows]=await Promise.all([db.prepare("SELECT data FROM settings WHERE user_id=?").bind(user.userId).first<{data:string}>(),db.prepare("SELECT id,kind,data FROM entries WHERE user_id=? ORDER BY rowid").bind(user.userId).all<{id:string,kind:string,data:string}>()]);return json({settings:prefs?JSON.parse(prefs.data):defaults,entries:rows.results.map(x=>({...x,data:JSON.parse(x.data)}))});}catch(e){console.error("Load failed",e);return json({error:"Your saved day is unavailable. Please try again."},503)}}
export async function POST(req:Request){const user=await getChatGPTUser();if(!user)return json({error:"Sign in to save your day."},401);if(!sameOrigin(req))return json({error:"Request origin is not allowed."},403);try{const raw=await req.text();if(raw.length>30000)return json({error:"Entry is too large."},413);const body=JSON.parse(raw);const db=database();if(body.action==="settings"){const data=settingsSchema.parse(body.data);await db.prepare("INSERT INTO settings(user_id,data) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data").bind(user.userId,JSON.stringify(data)).run();return json({ok:true,data});}
if(body.action==="upsert"){if(!Array.isArray(body.entries)||body.entries.length<1||body.entries.length>30)return json({error:"Invalid entries."},400);const clean=body.entries.map((e:any)=>{if(typeof e.id!=="string"||!/^[-a-zA-Z0-9]{1,80}$/.test(e.id)||!Object.hasOwn(schemas,e.kind))throw new Error("Invalid entry");return {id:e.id,kind:e.kind as Kind,data:schemas[e.kind as Kind].parse(e.data)}});if(!await hasRoom(db,user.userId,(clean as {id:string}[]).map(e=>e.id)))return json({error:FULL},413);await db.batch(clean.map((e:any)=>db.prepare("INSERT INTO entries(user_id,id,kind,data) VALUES(?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET kind=excluded.kind,data=excluded.data").bind(user.userId,e.id,e.kind,JSON.stringify(e.data))));return json({ok:true,entries:clean});}
if(body.action==="host-change"){const change=validateHostChange(body);if(!await hasRoom(db,user.userId,change.entries.map(e=>e.id)))return json({error:FULL},413);await db.batch([...change.entries.map(e=>db.prepare("INSERT INTO entries(user_id,id,kind,data) VALUES(?,?,?,?) ON CONFLICT(user_id,id) DO UPDATE SET kind=excluded.kind,data=excluded.data").bind(user.userId,e.id,e.kind,JSON.stringify(e.data))),...change.removeIds.map(id=>db.prepare("DELETE FROM entries WHERE user_id=? AND id=?").bind(user.userId,id))]);return json({ok:true,entries:change.entries});}
if(body.action==="remove"&&typeof body.id==="string"){await db.prepare("DELETE FROM entries WHERE user_id=? AND id=?").bind(user.userId,body.id).run();return json({ok:true});}return json({error:"Unknown action."},400);
}catch(e){if(e instanceof SyntaxError||(e as any)?.name==="ZodError"||(e as Error)?.message==="Invalid entry")return json({error:"Please check the entry and try again."},400);console.error("Save failed",e);return json({error:"Couldn't save. Your entry is still here; please try again."},503)}}
