"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,Mic,Square,Volume2,ShoppingBasket,Sparkles,Check,Send,ImagePlus,LoaderCircle,X,RotateCcw,AudioLines,Keyboard,AlertCircle} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Button} from "@/components/ui/button";
import {Switch} from "@/components/ui/switch";
import {today,displayTime,type Entry} from "@/lib/daywell";
import type {AppState} from "./use-daywell";
type Draft={summary:string,question:string|null,entries:Entry[],transcript?:string};
function details(e:Entry){const d=e.data;switch(e.kind){case "food":return `About ${Math.round(d.calories)} kcal · ${d.protein}g protein · ${d.carbs}g carbs · ${d.fat}g fat`;case "alarm":return `${displayTime(d.time)} · ${d.days.length?d.days.map((i:number)=>["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][i]).join(", "):"one time"}`;case "sleep":return `${displayTime(d.bedtime)} to ${displayTime(d.wakeTime)} · ${Math.floor(d.minutes/60)}h ${d.minutes%60}m`;case "grocery":return d.quantity;case "timer":return `${d.duration/60} minutes · starts when confirmed`;default:return `${d.minutes} minutes · ${d.date}`}}
export function CaptureHub({a}:{a:AppState}){
 const [open,setOpen]=useState(false),[connected,setConnected]=useState<boolean|null>(null),[mode,setMode]=useState("auto"),[text,setText]=useState(""),[typed,setTyped]=useState(false),[image,setImage]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[audioFile,setAudioFile]=useState<File|null>(null),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<Draft|null>(null),[context,setContext]=useState(""),[spoken,setSpoken]=useState(true),[saved,setSaved]=useState(false),[demo,setDemo]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null),audioRef=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),streamRef=useRef<MediaStream|null>(null),clockRef=useRef<ReturnType<typeof setInterval>|null>(null),abortRef=useRef<AbortController|null>(null),closed=useRef(false),session=useRef(0),micLock=useRef(false),saveLock=useRef(false),lock=useRef(false),current=useRef({result,context,spoken,mode});current.current={result,context,spoken,mode};
 const stopTracks=()=>{streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(clockRef.current)clearInterval(clockRef.current)};
 const speak=(value:string)=>{if(typeof window!=="undefined"&&"speechSynthesis" in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(value);utterance.rate=.98;speechSynthesis.speak(utterance)}};
 async function checkConnection(){try{const r=await fetch("/api/capture");const j:any=await r.json();setConnected(r.ok&&j.connected)}catch{setConnected(false)}}
 useEffect(()=>{void checkConnection();const onCapture=(event:Event)=>{const detail=(event as CustomEvent).detail||{};begin(detail.mode||"auto");};window.addEventListener("daywell-capture",onCapture);return ()=>{window.removeEventListener("daywell-capture",onCapture);closed.current=true;abortRef.current?.abort();if(recorder.current?.state==="recording"){recorder.current.onstop=null;recorder.current.stop()}stopTracks();if("speechSynthesis" in window)speechSynthesis.cancel()}},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 function begin(nextMode="auto"){closed.current=false;setDemo(false);setMode(nextMode);setOpen(true);setError("");setSaved(false);}
 function close(){session.current++;closed.current=true;abortRef.current?.abort();if(recorder.current?.state==="recording"){recorder.current.onstop=null;recorder.current.stop()}stopTracks();setRecording(false);setBusy(false);setOpen(false);setImage(null);setPreview(null);setAudioFile(null);setResult(null);setText("");setTyped(false);setContext("");if("speechSynthesis" in window)speechSynthesis.cancel()}
 async function chooseImage(file:File){setDemo(false);setError("");setResult(null);setSaved(false);if(!/^image\/(jpeg|png|webp)$/.test(file.type)){setError("Please choose a JPEG, PNG or WebP photo.");return}if(file.size>15*1024*1024){setError("Choose a photo under 15 MB.");return}try{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.85));if(!blob)throw Error("Couldn't open that photo.");const photo=new File([blob],"meal-or-list.jpg",{type:"image/jpeg"});setImage(photo);setPreview(URL.createObjectURL(photo));setAudioFile(null)}catch(e:any){setError(e.message||"Couldn't open that photo. Try another image.")}}
 async function analyse(input:{audio?:File,text?:string,image?:File,confirmOnly?:boolean}={}){if(lock.current)return;if(!connected){setError("AI analysis isn't connected yet. Connect the AI service to turn pictures and speech into entries.");return}lock.current=true;setBusy(true);setError("");setSaved(false);abortRef.current=new AbortController();let clarification:string|null=null;try{const form=new FormData();form.set("date",today());form.set("time",new Date().toLocaleTimeString());form.set("mode",current.current.mode);form.set("context",current.current.context);form.set("text",input.text??text);const chosenImage=input.image??image;if(chosenImage)form.set("image",chosenImage);if(input.audio)form.set("audio",input.audio);if(input.confirmOnly)form.set("confirmOnly","true");const r=await fetch("/api/capture",{method:"POST",body:form,signal:abortRef.current.signal});const value:any=await r.json();if(!r.ok)throw Error(value.error);if(closed.current)return;
 if(input.confirmOnly&&current.current.result?.entries.length){if(value.confirm){await confirm(current.current.result);return}clarification=value.transcript;setText(value.transcript);return}
 setResult(value);setContext(`${current.current.context}\nUser: ${value.transcript||input.text||text||"Photo"}\nAssistant: ${JSON.stringify(value)}`.slice(-8000));setText("");setAudioFile(null);if(current.current.spoken)speak(value.question||value.summary);
 }catch(e:any){if(e.name!=="AbortError")setError(e.message||"That didn't work. Your capture is still here; please retry.")}finally{lock.current=false;setBusy(false);if(clarification!==null&&!closed.current)void analyse({text:clarification})}}
 async function confirm(draft=result){if(!draft?.entries.length||saveLock.current)return;if(demo){setSaved(true);setResult(null);if(spoken)speak("Example complete. In the connected app, your confirmed entries would now be saved.");return}saveLock.current=true;const token=session.current;setBusy(true);a.unlockAudio();const list=draft.entries.map(e=>e.kind==="timer"?{...e,data:{...e.data,endAt:Date.now()+e.data.duration*1000}}:e);const done=await a.save(list);saveLock.current=false;if(closed.current||session.current!==token)return;if(done){setSaved(true);setResult(null);setImage(null);setPreview(null);setAudioFile(null);setContext("");setText("");if(spoken)speak(`All set. ${list.length===1?"That's":"Those are"} saved to your day.`)}setBusy(false)}
 async function startRecording(){if(micLock.current||recorder.current?.state==="recording")return;setError("");setSaved(false);if(!connected){begin(mode);setError("Voice understanding needs the AI connection first. No audio has been recorded.");return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){setError("Recording isn't supported in this browser. You can attach an audio file instead.");return}micLock.current=true;const token=session.current;try{if("speechSynthesis" in window)speechSynthesis.cancel();const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(closed.current||session.current!==token){stream.getTracks().forEach(t=>t.stop());return}streamRef.current=stream;const mime=["audio/webm;codecs=opus","audio/mp4","audio/webm"].find(x=>MediaRecorder.isTypeSupported(x));const rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);recorder.current=rec;const chunks:BlobPart[]=[];let size=0;rec.ondataavailable=e=>{if(e.data.size){size+=e.data.size;chunks.push(e.data);if(size>8*1024*1024&&rec.state==="recording")rec.stop()}};const confirming=!!current.current.result?.entries.length;rec.onstop=()=>{stopTracks();setRecording(false);if(closed.current)return;const blob=new Blob(chunks,{type:rec.mimeType});const f=new File([blob],rec.mimeType.includes("mp4")?"voice.mp4":"voice.webm",{type:rec.mimeType});setAudioFile(f);void analyse({audio:f,confirmOnly:confirming})};rec.onerror=()=>{stopTracks();setRecording(false);setError("The microphone stopped. Please try recording again.")};rec.start(250);setSeconds(0);setRecording(true);const start=Date.now();clockRef.current=setInterval(()=>{const elapsed=Math.floor((Date.now()-start)/1000);setSeconds(elapsed);if(elapsed>=30&&rec.state==="recording")rec.stop()},250)}catch(e:any){stopTracks();setRecording(false);setError(e.name==="NotAllowedError"?"Microphone access wasn't allowed. Enable it in your browser, or attach an audio file.":"Couldn't start the microphone. Please check it's connected and try again.")}finally{micLock.current=false}}
 function showExample(kind="meal"){begin(kind);setDemo(true);setError("");setImage(null);setAudioFile(null);setText("");setContext("");const food:Entry={id:"example-food",kind:"food",data:{title:"Salmon & quinoa bowl",date:today(),meal:"Lunch",calories:620,protein:40,carbs:52,fat:28}};const examples:Record<string,Draft>={meal:{summary:"This looks like salmon, quinoa and vegetables. I estimate about 620 calories for this example portion. Shall I add it as lunch?",question:null,entries:[food]},auto:{summary:"A 20-minute walk for today, and a 25-minute focus timer. Shall I save the walk and start your timer?",question:null,transcript:"I walked for twenty minutes. Start a twenty-five minute focus timer.",entries:[{id:"example-move",kind:"move",data:{title:"Walk",date:today(),minutes:20}},{id:"example-timer",kind:"timer",data:{title:"Focus time",duration:1500,remaining:1500,endAt:null,mode:"Focus"}}]},grocery:{summary:"Milk, six eggs and a loaf of sourdough. Shall I add these three items to your shopping list?",question:null,transcript:"We need milk, six eggs and a loaf of sourdough.",entries:["Milk","Eggs","Sourdough"].map((title,i)=>({id:`example-${i}`,kind:"grocery",data:{title,quantity:["1 bottle","6","1 loaf"][i],done:false}}))}};setPreview(kind==="meal"?"/grain-bowl.jpg":null);setResult(examples[kind]||examples.meal)}
 const examples=[{mode:"meal",icon:Camera,title:"Show your meal",detail:"A photo becomes a food log"},{mode:"auto",icon:Mic,title:"Tell me about your day",detail:'“I walked for twenty minutes”'},{mode:"grocery",icon:ShoppingBasket,title:"Snap a shopping list",detail:"Turn a picture into your list"}];
 return <><section className={a.active==="today"?"capture-hero":"capture-bar"}><div className="capture-copy"><span className="capture-kicker"><Sparkles size={14}/> YOUR DAY, WITHOUT THE DATA ENTRY</span><h2>Life happens.<br/> Just tell Daywell.</h2><p>Show a picture. Say a few words.<br/> We'll take care of the details.</p><div className="capture-actions"><button className="talk-button" onClick={()=>{begin("auto");void startRecording()}}><Mic size={20}/>Talk to Daywell</button><button className="snap-button" onClick={()=>{begin(a.active==="grocery"?"grocery":"meal");fileRef.current?.click()}}><Camera size={20}/>Take a photo</button></div><span className="capture-status">{connected===null?"Checking connection…":connected?"Ready when you are · tap to begin":"Preview · AI connection needed"}</span></div><div className="capture-visual"><div className="capture-photo"><img src="/grain-bowl.jpg" alt="An example salmon and quinoa lunch"/><span><Camera size={14}/>A picture is all it takes.</span></div><div className="voice-note"><span className="voice-note-icon"><AudioLines size={22}/></span><div><small>JUST SAY IT</small><p>“Add milk and eggs to my list.”</p></div><span className="voice-dot"/></div><span className="visual-caption">DESIGNED AROUND REAL LIFE</span></div><div className="capture-examples">{examples.map(e=><button key={e.title} onClick={()=>connected?begin(e.mode):showExample(e.mode)}><span><e.icon size={20}/></span><div><strong>{e.title}</strong><small>{connected?e.detail:"Try a guided example"}</small></div></button>)}</div></section>
 <input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{const file=e.target.files?.[0];if(file)void chooseImage(file);e.target.value=""}}/>
 <Dialog open={open} onOpenChange={value=>{if(!value)close()}}><DialogContent className="capture-dialog"><DialogHeader><div className="capture-dialog-top"><span className="modal-mark"><AudioLines size={24}/></span><label className="spoken-toggle"><Volume2 size={17}/><span>Spoken replies</span><Switch aria-label="Spoken replies" checked={spoken} onCheckedChange={setSpoken}/></label></div><DialogTitle>{saved?(demo?"Example complete.":"Taken care of."):recording?"I'm listening.":busy?"Making sense of your day…":result?.question?"One quick question.":result?.entries.length?"Here's what I understood.":"Show it. Say it. Sorted."}</DialogTitle><DialogDescription>{saved?(demo?"This shows the flow. No example entries were saved.":"Your entry is now in the right place."):recording?"Speak naturally, then tap stop. Up to 30 seconds.":"Food, tasks, sleep, movement, shopping, alarms and timers."}</DialogDescription></DialogHeader>
 {demo&&<div className="demo-label"><Sparkles size={15}/>GUIDED EXAMPLE · SAMPLE CONTENT</div>}
 {connected===false&&!demo&&<div className="capture-warning"><AlertCircle size={18}/><div><strong>AI isn't connected yet.</strong><p>Photo and voice understanding will work once the AI service is connected. Try a guided example below.</p><div className="demo-links"><button onClick={()=>showExample("meal")}>Meal photo</button><button onClick={()=>showExample("auto")}>Voice request</button><button onClick={()=>showExample("grocery")}>Shopping list</button></div></div><Button variant="ghost" size="icon" aria-label="Recheck AI connection" onClick={()=>void checkConnection()}><RotateCcw size={16}/></Button></div>}
 {saved?<div className="capture-success"><Check size={40}/><p>Less logging. More living.</p><Button variant="outline" onClick={()=>demo?close():setSaved(false)}>{demo?"Back to my day":"Something else?"}</Button></div>:<>
 {!result?.entries.length&&!recording&&!busy&&<div className="capture-mode"><button className={mode==="meal"?"selected":""} onClick={()=>setMode("meal")}>Meal photo</button><button className={mode==="grocery"?"selected":""} onClick={()=>setMode("grocery")}>Shopping list</button><button className={mode==="auto"?"selected":""} onClick={()=>setMode("auto")}>Anything else</button></div>}
 {preview&&!saved&&<div className="capture-preview"><img src={preview} alt="Your photo ready for analysis"/><button aria-label="Remove photo" onClick={()=>demo?close():((()=>{setImage(null);setPreview(null);setResult(null)})())}><X size={16}/></button></div>}
 {recording&&<div className="listening"><div className="sound-bars">{[1,2,3,4,5,6,7,8,9].map(n=><i key={n} style={{animationDelay:`${n*.12}s`}}/>)}</div><strong>00:{String(seconds).padStart(2,"0")}</strong><button onClick={()=>recorder.current?.stop()}><Square fill="currentColor" size={16}/>Stop & understand</button></div>}
 {busy&&<div className="capture-busy"><LoaderCircle className="spin" size={25}/><span>{result?.entries.length?"Saving your entry…":"Understanding your capture…"}</span></div>}
 {result&&<div className="capture-result"><div className="reply-bubble"><Sparkles size={18}/><p>{result.question||result.summary}</p><button aria-label="Read response aloud" onClick={()=>speak(result.question||result.summary)}><Volume2 size={18}/></button></div>{result.transcript&&<p className="transcript">You said: “{result.transcript}”</p>}{result.entries.map(e=><div className="draft-entry" key={e.id}><span>{e.kind==="task"?"Productivity":e.kind}</span><strong>{e.data.title||"Sleep"}</strong><small>{details(e)}</small></div>)}</div>}
 {!busy&&!recording&&<>{result?.entries.length?<div className="confirmation-actions"><Button disabled={a.saving>0} onClick={()=>void confirm()}><Check/>{demo?"Finish example":`Yes, save ${result.entries.length===1?"that":"these"}`}</Button>{demo?<Button variant="outline" onClick={()=>speak(result.summary)}><Volume2/>Hear Daywell reply</Button>:<><Button variant="outline" onClick={()=>void startRecording()}><Mic/>Say yes or correct me</Button><button className="quiet-action" onClick={()=>{setTyped(true);setResult(null)}}>Change something</button></>}</div>:<div className="capture-inputs">{!preview&&<button className="large-camera" onClick={()=>fileRef.current?.click()}><ImagePlus size={28}/><span>Add a photo</span></button>}<button className="large-mic" onClick={()=>void startRecording()}><Mic size={29}/><span>{result?.question?"Speak your answer":"Tap to talk"}</span></button>{preview&&<Button className="analyse-button" onClick={()=>void analyse({image:image!})}><Sparkles/>Understand this photo</Button>}</div>}
 {(typed||result?.question)&&<form className="capture-text" onSubmit={e=>{e.preventDefault();void analyse({text})}}><input aria-label="Message to Daywell" placeholder={result?.question?"Or type your answer…":"Tell Daywell what you need…"} value={text} onChange={e=>setText(e.target.value)} maxLength={6000}/><button aria-label="Send message" disabled={!text.trim()} type="submit"><Send size={18}/></button></form>}
 <div className={`capture-alternatives ${demo?"hidden":""}`}><button onClick={()=>setTyped(!typed)}><Keyboard size={15}/>Type instead</button><button onClick={()=>audioRef.current?.click()}><AudioLines size={15}/>Attach audio</button>{audioFile&&<button onClick={()=>void analyse({audio:audioFile,confirmOnly:!!result?.entries.length})}><RotateCcw size={15}/>Retry recording</button>}</div></>}
 </>}{error&&<p className="form-error" role="alert">{error}</p>}<input ref={audioRef} className="sr-only" type="file" accept="audio/*" onChange={e=>{const file=e.target.files?.[0];if(file){setAudioFile(file);void analyse({audio:file,confirmOnly:!!result?.entries.length})}e.target.value=""}}/><p className="capture-privacy">{demo?"Sample content demonstrates the proposed experience. Live picture and voice understanding is not connected.":"Photos and recordings are sent to the AI service when you ask it to understand them. Daywell saves only the entries you confirm."}</p></DialogContent></Dialog></>;
}

