"use client";
import {useState} from "react";
import {Sun,Palette,CalendarDays,LayoutGrid,Timer,AlarmClock,ListChecks,Moon,ShoppingBasket,Utensils,Footprints,SlidersHorizontal,Plus,Sparkles,ChevronRight,LoaderCircle,CloudCheck,AlertCircle} from "lucide-react";
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from "@/components/ui/sidebar";
import {Button} from "@/components/ui/button";
import {Toaster} from "sonner";
import {today,displayTime,type Entry} from "@/lib/daywell";
import {useDaywell} from "./use-daywell";
import {FocusCard,FoodCard,TaskRows,Empty} from "./parts";
import {PillarWorkspace} from "./pillar-workspace";
import {Dialogs} from "./dialogs";
import {WelcomeFlow} from "./wellbeing-welcome";
import {FirstSteps} from "./first-steps";
import {DaySnapshot,QuickEntry} from "./everyday";
import {filterTasks} from "@/lib/routines";
import {DaywellHost} from "./daywell-host";
import {CalendarWorkspace} from "./calendar-workspace";
import {useDaywellStyle} from "./design-switcher";
import {AppearanceStudio,IterationReview} from "./appearance-studio";
import {StillwaterNavigation} from "./stillwater-navigation";

import {CompanionPortrait} from "@/components/daywell-companions";
import {companionForModule} from "@/lib/companions";
export const modules=[{id:"alarm",name:"Alarm",icon:AlarmClock,color:"#e99a31",desc:"Wake up with intention"},{id:"clock",name:"Clock & timers",icon:Timer,color:"#4079ed",desc:"Give your time a little structure"},{id:"focus",name:"Productivity",icon:ListChecks,color:"#5a55e6",desc:"Make space for your priorities"},{id:"sleep",name:"Sleep",icon:Moon,color:"#8867db",desc:"Build a gentler evening"},{id:"grocery",name:"Groceries",icon:ShoppingBasket,color:"#109478",desc:"A clear list, an easier shop"},{id:"food",name:"Food & nutrition",icon:Utensils,color:"#df7544",desc:"Get to know your daily fuel"},{id:"move",name:"Movement",icon:Footprints,color:"#bb5796",desc:"Small moves, a better day"}];
function NavButton({onClick,children,...props}:any){const {setOpenMobile}=useSidebar();return <SidebarMenuButton {...props} onClick={()=>{onClick();setOpenMobile(false)}}>{children}</SidebarMenuButton>}
export default function Daywell({showWelcome=false,initialView="today"}:{showWelcome?:boolean;initialView?:string}){const look=useDaywellStyle(),[choosingStyle,setChoosingStyle]=useState(false),[reviewingDesigns,setReviewingDesigns]=useState(false),showStyles=choosingStyle,cozy=look.style==="nook",immersive=look.style==="stillwater"||cozy;const a=useDaywell(showWelcome,initialView),{settings,active,enabled}=a,selected=modules.filter(m=>enabled(m.id));const dateLabel=new Date(a.now).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});

 if(a.loaded&&a.welcome)return <><WelcomeFlow a={a}/><Toaster position="bottom-right" richColors/></>;
 return <SidebarProvider className={cozy?"nook-shell":immersive?"stillwater-shell":undefined} style={{"--sidebar-width":"238px"} as React.CSSProperties}>{!immersive&&<Sidebar className="dw-sidebar"><SidebarHeader><div className="brand"><span><Sun size={23}/></span>daywell<span className="brand-dot">.</span></div></SidebarHeader><SidebarContent><SidebarMenu><SidebarMenuItem><NavButton isActive={active==="today"} onClick={()=>a.setActive("today")}><LayoutGrid/>Today</NavButton></SidebarMenuItem><SidebarMenuItem><NavButton isActive={active==="calendar"} onClick={()=>a.setActive("calendar")}><CalendarDays/>Calendar & history</NavButton></SidebarMenuItem></SidebarMenu><p className="nav-label">Your tools</p><SidebarMenu>{selected.map(m=><SidebarMenuItem key={m.id}><NavButton isActive={active===m.id} onClick={()=>a.setActive(m.id)}><m.icon style={{color:m.color}}/>{m.name}</NavButton></SidebarMenuItem>)}</SidebarMenu><button className="manage-side" onClick={()=>{a.setPrefs(settings);a.setCustomize(true)}}><Plus size={16}/>Manage your tools</button></SidebarContent><SidebarFooter><div className="side-note"><Sparkles size={18}/><strong>A little more balance.</strong><p>Make room for what matters today.</p></div><div className="profile"><span>{settings.name.slice(0,1).toUpperCase()}</span><div><strong>{settings.name==="You"?"Your space":settings.name}</strong><small>Personal workspace</small></div></div></SidebarFooter></Sidebar>}<main className="workspace host-workspace" data-view={active}>{immersive&&<StillwaterNavigation a={a} tools={selected} onStyle={()=>{setChoosingStyle(true);requestAnimationFrame(()=>document.getElementById("daywell-design-picker")?.scrollIntoView({block:"start",behavior:"instant"}))}}/>}<header className="topbar"><div><SidebarTrigger/><span>Your everyday, together</span></div><div className="top-actions"><Button id="daywell-style-toggle" className="style-toggle" variant="outline" aria-expanded={showStyles} aria-controls="daywell-design-picker" onClick={()=>setChoosingStyle(!showStyles)}><Palette size={16}/>Your style</Button><Button className="getting-started-button" variant="ghost" aria-label="Getting started" title="Getting started" disabled={!a.loaded} onClick={()=>{a.setPrefs(settings);a.setFormError("");a.setWelcome(true)}}><Sparkles size={16}/><span className="getting-started-label">Getting started</span></Button><span className="save-status" role="status">{a.syncError?<><AlertCircle size={15}/>Not saved</>:a.saving?<><LoaderCircle className="spin" size={14}/>Saving</>:a.loaded?<><CloudCheck size={15}/>Saved</>:null}</span><Button variant="outline" aria-label="Customize tools" disabled={!a.loaded} onClick={()=>{a.setPrefs(settings);a.setFormError("");a.setCustomize(true)}}><SlidersHorizontal/><span className="top-tools-long">Customize tools</span><span className="top-tools-short">Tools</span></Button></div></header><div className="page">
 {a.loadError&&<div className="error-banner" role="alert"><AlertCircle/><span>{a.loadError}</span><Button variant="outline" onClick={()=>void a.load()}>Try again</Button></div>}
 <div className="page-heading"><div><div className="eyebrow">{active==="today"?dateLabel:"Your everyday tools"}</div><h1>{active==="today"?(settings.name==="You"?"Make today feel good":`Your day, ${settings.name}`):active==="calendar"?"Calendar & history":modules.find(m=>m.id===active)?.name}<span>.</span></h1><p>{active==="today"?"Take it one thing at a time.":active==="calendar"?"Make plans. Remember your progress.":modules.find(m=>m.id===active)?.desc}</p></div>{active==="today"&&<span className="date-pill"><Sun size={18}/>Your own pace</span>}</div>
 {!a.loaded&&!a.loadError&&<div className="loading-state"><LoaderCircle className="spin"/>Opening your space…</div>}
 {a.loaded&&showStyles&&<AppearanceStudio look={look} name={settings.name} onDone={()=>setChoosingStyle(false)} onTry={()=>{setReviewingDesigns(true);setChoosingStyle(false);a.setActive("today");requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"instant"}))}}/>}
 {a.loaded&&reviewingDesigns&&active==="today"&&<IterationReview look={look} onCompare={()=>setChoosingStyle(true)} onClose={()=>setReviewingDesigns(false)}/>}
 {a.loaded&&<details className={active==="calendar"||(immersive&&active!=="today")?"calendar-host-disclosure":"calendar-host-always"} open={active!=="calendar"&&(!immersive||active==="today")}><summary>Talk or type to Daywell<span>One host, wherever you are</span></summary><DaywellHost a={a} immersive={immersive} cozy={cozy} company={look.current.company}/></details>}
 {a.loaded&&active==="calendar"&&<CalendarWorkspace a={a}/>}
 {a.loaded&&active==="today"&&<button className="calendar-home-link" onClick={()=>a.setActive("calendar")}><CalendarDays size={19}/><span>Calendar & history<small>What’s next, and how far you’ve come</small></span><ChevronRight size={17}/></button>}
 {a.loaded&&active==="today"&&<details className="host-tools"><summary>Your tools & saved day<span>Here whenever you need them</span></summary><TodayTools a={a}/></details>}
 {a.loaded&&active!=="today"&&active!=="calendar"&&<PillarWorkspace key={active} a={a}/>}<footer className="page-footer"><Sun size={15}/>Small steps. Better days.</footer></div></main><Dialogs a={a} modules={modules}/><Toaster position="bottom-right" richColors/></SidebarProvider>;
}

function TodayTools({a}:{a:ReturnType<typeof useDaywell>}){const {enabled,settings}=a,selected=modules.filter(m=>enabled(m.id)),tasks=filterTasks(a.entries,"today",today()),sleep=a.dayEntries("sleep").at(-1),movement=a.dayEntries("move").reduce((n,e)=>n+e.data.minutes,0),focused=a.dayEntries("session").reduce((n,e)=>n+e.data.minutes,0); function buildPlan(){const suggestions:Entry[]=[];if(!tasks.some(e=>!e.data.done))suggestions.push({id:crypto.randomUUID(),kind:"task",data:{title:"Choose and finish one meaningful priority",done:false,date:today(),minutes:25}});if(enabled("move"))suggestions.push({id:crypto.randomUUID(),kind:"task",data:{title:"Take a 15-minute walk",done:false,date:today(),minutes:15}});if(enabled("sleep"))suggestions.push({id:crypto.randomUUID(),kind:"task",data:{title:`Start winding down at ${displayTime(settings.bedtime)}`,done:false,date:today(),minutes:15}});a.setPlan(suggestions.filter(s=>!a.dayEntries("task").some(e=>e.data.title===s.data.title)))}
 return <><FirstSteps a={a}/><DaySnapshot a={a}/><div className={`overview-grid ${!enabled("food")||!enabled("focus")?"single":""}`}>{enabled("focus")&&<FocusCard a={a}/>} {enabled("food")&&<FoodCard a={a}/>} {!enabled("focus")&&!enabled("food")&&<section className="welcome-card"><Sun size={32}/><h2>A little room for you.</h2><p>Your tools are ready. Pick one below to begin.</p></section>}</div><div className="bottom-grid">{enabled("focus")&&<section className="card"><div className="section-title"><h2>Your priorities <span className="count">{tasks.length} to do</span></h2><Button variant="ghost" onClick={()=>a.openEditor("task")}><Plus/>Add task</Button></div><QuickEntry a={a} kind="task"/>{tasks.length?<TaskRows a={a} items={tasks.slice(0,4)}/>:<Empty title="Clear mind, fresh page." description="Add your first priority for today."/>}<div className="card-foot"><span>{focused} minutes of focus today</span><button onClick={()=>a.setActive("focus")}>View all<ChevronRight size={14}/></button></div></section>}<section className="card daily-rhythm"><div className="section-title"><h2>A gentler rhythm</h2><Sun size={21}/></div>{enabled("sleep")&&<button className="rhythm-item" onClick={()=>a.setActive("sleep")}><span className="icon-box purple"><Moon size={20}/></span><div><strong>{sleep?`${Math.floor(sleep.data.minutes/60)}h ${sleep.data.minutes%60}m of sleep`:`Wind down at ${displayTime(settings.bedtime)}`}</strong><p>{sleep?`Feeling ${sleep.data.quality.toLowerCase()} today.`:"Make space for a restful evening."}</p></div><ChevronRight size={15}/></button>}{enabled("move")&&<button className="rhythm-item" onClick={()=>a.setActive("move")}><span className="icon-box mint"><Footprints size={20}/></span><div><strong>{movement?`${movement} minutes of movement`:"Make a little movement"}</strong><p>{movement?"Every little bit counts.":"A short walk is a good place to start."}</p></div><ChevronRight size={15}/></button>}{enabled("grocery")&&<button className="rhythm-item" onClick={()=>a.setActive("grocery")}><span className="icon-box peach"><ShoppingBasket size={20}/></span><div><strong>{a.by("grocery").filter(e=>!e.data.done).length} items on your list</strong><p>One less thing to keep in your head.</p></div><ChevronRight size={15}/></button>}{!enabled("sleep")&&!enabled("move")&&!enabled("grocery")&&<p className="rhythm-empty">Build your day one small step at a time.</p>}{enabled("focus")&&<button className="plan-link" onClick={buildPlan}><Sparkles size={16}/>Suggest a simple day plan</button>}</section></div><div className="section-title tools-heading"><h2>Your everyday toolkit</h2><span className="muted">Made to work your way.</span></div><div className="module-grid">{selected.map(m=><button key={m.id} className="module-card" onClick={()=>a.setActive(m.id)}><CompanionPortrait id={companionForModule[m.id]} size={60} decorative/><strong>{m.name}</strong></button>)}</div></>;
}
