"use client";
import {Sun,LayoutGrid,Timer,AlarmClock,ListChecks,Moon,ShoppingBasket,Utensils,Footprints,SlidersHorizontal,Plus,Sparkles,ChevronRight,LoaderCircle,CloudCheck,AlertCircle} from "lucide-react";
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from "@/components/ui/sidebar";
import {Button} from "@/components/ui/button";
import {Toaster} from "sonner";
import {today,displayTime,type Entry} from "@/lib/daywell";
import {useDaywell} from "./use-daywell";
import {FocusCard,FoodCard,TaskRows,Empty} from "./parts";
import {ModuleView} from "./modules";
import {Dialogs} from "./dialogs";
import {DaySnapshot,QuickEntry} from "./everyday";
import {filterTasks} from "@/lib/routines";
import {CaptureHub} from "./capture-hub";
export const modules=[{id:"alarm",name:"Alarm",icon:AlarmClock,color:"#e99a31",desc:"Wake up with intention"},{id:"clock",name:"Clock & timers",icon:Timer,color:"#4079ed",desc:"Give your time a little structure"},{id:"focus",name:"Productivity",icon:ListChecks,color:"#5a55e6",desc:"Make space for your priorities"},{id:"sleep",name:"Sleep",icon:Moon,color:"#8867db",desc:"Build a gentler evening"},{id:"grocery",name:"Groceries",icon:ShoppingBasket,color:"#109478",desc:"A clear list, an easier shop"},{id:"food",name:"Food & nutrition",icon:Utensils,color:"#df7544",desc:"Get to know your daily fuel"},{id:"move",name:"Movement",icon:Footprints,color:"#bb5796",desc:"Small moves, a better day"}];
function NavButton({onClick,children,...props}:any){const {setOpenMobile}=useSidebar();return <SidebarMenuButton {...props} onClick={()=>{onClick();setOpenMobile(false)}}>{children}</SidebarMenuButton>}
export default function Daywell(){const a=useDaywell(),{settings,active,enabled}=a,selected=modules.filter(m=>enabled(m.id)),tasks=filterTasks(a.entries,"today",today()),sleep=a.dayEntries("sleep").at(-1),movement=a.dayEntries("move").reduce((n,e)=>n+e.data.minutes,0),focused=a.dayEntries("session").reduce((n,e)=>n+e.data.minutes,0);const dateLabel=new Date(a.now).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"});
 function buildPlan(){const suggestions:Entry[]=[];if(!tasks.some(e=>!e.data.done))suggestions.push({id:crypto.randomUUID(),kind:"task",data:{title:"Choose and finish one meaningful priority",done:false,date:today(),minutes:25}});if(enabled("move"))suggestions.push({id:crypto.randomUUID(),kind:"task",data:{title:"Take a 15-minute walk",done:false,date:today(),minutes:15}});if(enabled("sleep"))suggestions.push({id:crypto.randomUUID(),kind:"task",data:{title:`Start winding down at ${displayTime(settings.bedtime)}`,done:false,date:today(),minutes:15}});a.setPlan(suggestions.filter(s=>!a.dayEntries("task").some(e=>e.data.title===s.data.title)))}
 return <SidebarProvider style={{"--sidebar-width":"238px"} as React.CSSProperties}><Sidebar className="dw-sidebar"><SidebarHeader><div className="brand"><span><Sun size={23}/></span>daywell<span className="brand-dot">.</span></div></SidebarHeader><SidebarContent><SidebarMenu><SidebarMenuItem><NavButton isActive={active==="today"} onClick={()=>a.setActive("today")}><LayoutGrid/>Today</NavButton></SidebarMenuItem></SidebarMenu><p className="nav-label">YOUR TOOLS</p><SidebarMenu>{selected.map(m=><SidebarMenuItem key={m.id}><NavButton isActive={active===m.id} onClick={()=>a.setActive(m.id)}><m.icon style={{color:m.color}}/>{m.name}</NavButton></SidebarMenuItem>)}</SidebarMenu><button className="manage-side" onClick={()=>{a.setPrefs(settings);a.setCustomize(true)}}><Plus size={16}/>Manage your tools</button></SidebarContent><SidebarFooter><div className="side-note"><Sparkles size={18}/><strong>A little more balance.</strong><p>Make room for what matters today.</p></div><div className="profile"><span>{settings.name.slice(0,1).toUpperCase()}</span><div><strong>{settings.name==="You"?"Your space":settings.name}</strong><small>Personal workspace</small></div></div></SidebarFooter></Sidebar><main className="workspace"><header className="topbar"><div><SidebarTrigger/><span>Your everyday, together</span></div><div className="top-actions"><span className="save-status" role="status">{a.syncError?<><AlertCircle size={15}/>Not saved</>:a.saving?<><LoaderCircle className="spin" size={14}/>Saving</>:a.loaded?<><CloudCheck size={15}/>Saved</>:null}</span><Button variant="outline" disabled={!a.loaded} onClick={()=>{a.setPrefs(settings);a.setFormError("");a.setCustomize(true)}}><SlidersHorizontal/>Customize tools</Button></div></header><div className="page">
 {a.loadError&&<div className="error-banner" role="alert"><AlertCircle/><span>{a.loadError}</span><Button variant="outline" onClick={()=>void a.load()}>Try again</Button></div>}
 <div className="page-heading"><div><div className="eyebrow">{active==="today"?dateLabel.toUpperCase():"YOUR EVERYDAY TOOLKIT"}</div><h1>{active==="today"?(settings.name==="You"?"Make today feel good":`Your day, ${settings.name}`):modules.find(m=>m.id===active)?.name}<span>.</span></h1><p>{active==="today"?"A little focus. A little fuel. A little time for you.":modules.find(m=>m.id===active)?.desc}</p></div>{active==="today"&&<span className="date-pill"><Sun size={18}/>{selected.length} tools, one balanced day</span>}</div>
 {!a.loaded&&!a.loadError&&<div className="loading-state"><LoaderCircle className="spin"/>Opening your space…</div>}
 {a.loaded&&active==="today"&&<DaySnapshot a={a}/>}
 {a.loaded&&active!=="today"&&<CaptureHub a={a}/>}
 {a.loaded&&active==="today"&&<><div className={`overview-grid ${!enabled("food")||!enabled("focus")?"single":""}`}>{enabled("focus")&&<FocusCard a={a}/>} {enabled("food")&&<FoodCard a={a}/>} {!enabled("focus")&&!enabled("food")&&<section className="welcome-card"><Sun size={32}/><h2>A little room for you.</h2><p>Your tools are ready. Pick one below to begin.</p></section>}</div><div className="bottom-grid">{enabled("focus")&&<section className="card"><div className="section-title"><h2>Your priorities <span className="count">{tasks.length} to do</span></h2><Button variant="ghost" onClick={()=>a.openEditor("task")}><Plus/>Add task</Button></div><QuickEntry a={a} kind="task"/>{tasks.length?<TaskRows a={a} items={tasks.slice(0,4)}/>:<Empty title="Clear mind, fresh page." description="Add your first priority for today."/>}<div className="card-foot"><span>{focused} minutes of focus today</span><button onClick={()=>a.setActive("focus")}>View all<ChevronRight size={14}/></button></div></section>}<section className="card daily-rhythm"><div className="section-title"><h2>A gentler rhythm</h2><Sun size={21}/></div>{enabled("sleep")&&<button className="rhythm-item" onClick={()=>a.setActive("sleep")}><span className="icon-box purple"><Moon size={20}/></span><div><strong>{sleep?`${Math.floor(sleep.data.minutes/60)}h ${sleep.data.minutes%60}m of sleep`:`Wind down at ${displayTime(settings.bedtime)}`}</strong><p>{sleep?`Feeling ${sleep.data.quality.toLowerCase()} today.`:"Make space for a restful evening."}</p></div><ChevronRight size={15}/></button>}{enabled("move")&&<button className="rhythm-item" onClick={()=>a.setActive("move")}><span className="icon-box mint"><Footprints size={20}/></span><div><strong>{movement?`${movement} minutes of movement`:"Make a little movement"}</strong><p>{movement?"Every little bit counts.":"A short walk is a good place to start."}</p></div><ChevronRight size={15}/></button>}{enabled("grocery")&&<button className="rhythm-item" onClick={()=>a.setActive("grocery")}><span className="icon-box peach"><ShoppingBasket size={20}/></span><div><strong>{a.by("grocery").filter(e=>!e.data.done).length} items on your list</strong><p>One less thing to keep in your head.</p></div><ChevronRight size={15}/></button>}{!enabled("sleep")&&!enabled("move")&&!enabled("grocery")&&<p className="rhythm-empty">Build your day one small step at a time.</p>}{enabled("focus")&&<button className="plan-link" onClick={buildPlan}><Sparkles size={16}/>Suggest a simple day plan</button>}</section></div><div className="dashboard-capture"><CaptureHub a={a}/></div><div className="section-title tools-heading"><h2>Your everyday toolkit</h2><span className="muted">Made to work your way.</span></div><div className="module-grid">{selected.map(m=><button key={m.id} className="module-card" onClick={()=>a.setActive(m.id)}><span className="module-num">0{modules.indexOf(m)+1}</span><m.icon size={25} style={{color:m.color}}/><strong>{m.name}</strong></button>)}</div></>}
 {a.loaded&&active!=="today"&&<ModuleView a={a}/>}<footer className="page-footer"><Sun size={15}/>Small steps. Better days.</footer></div></main><Dialogs a={a} modules={modules}/><Toaster position="bottom-right" richColors/></SidebarProvider>;
}
