"use client";
import {Sun,Check,LoaderCircle,Camera,X,AlarmClock} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Checkbox} from "@/components/ui/checkbox";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {toast} from "sonner";
import {sleepMinutes} from "@/lib/daywell";
import type {AppState} from "./use-daywell";
import {Field,Pick} from "./parts";
import type {WorkoutSet} from "@/lib/wellbeing";
export function Dialogs({a,modules}:{a:AppState,modules:any[]}){const {settings,prefs,editor,draft,photo,plan,ring}=a;const field=(key:string,value:any)=>a.setDraft((d:any)=>({...d,[key]:value}));
 return <><Dialog open={a.customize} onOpenChange={open=>{if(settings.onboarded)a.setCustomize(open)}}><DialogContent className="settings-dialog" showCloseButton={settings.onboarded}><DialogHeader><div className="modal-mark"><Sun size={24}/></div><DialogTitle>{settings.onboarded?"Make this space yours.":"A better day starts with you."}</DialogTitle><DialogDescription>Adjust your name, routines and optional everyday tools.</DialogDescription></DialogHeader><div className="settings-scroll"><Field label="What should we call you?"><input value={prefs.name==="You"?"":prefs.name} placeholder="Your name" maxLength={40} onChange={e=>a.setPrefs(p=>({...p,name:e.target.value||"You"}))}/></Field><div className="preset-row"><button onClick={()=>a.setPrefs(p=>({...p,modules:modules.map(m=>m.id) as any}))}>All tools</button><button onClick={()=>a.setPrefs(p=>({...p,modules:["clock","focus"]}))}>Focus mode</button><button onClick={()=>a.setPrefs(p=>({...p,modules:["sleep","grocery","food","move"]}))}>Feel-good mode</button></div><div className="choose-grid">{modules.map(m=><label className={`choose-module ${prefs.modules.includes(m.id)?"chosen":""}`} key={m.id}><span className="choice-icon" style={{color:m.color}}><m.icon size={21}/></span><span><strong>{m.name}</strong><small>{m.desc}</small></span><Checkbox checked={prefs.modules.includes(m.id)} onCheckedChange={checked=>a.setPrefs(p=>({...p,modules:checked?[...p.modules,m.id]:p.modules.filter(id=>id!==m.id)}))} aria-label={m.name}/></label>)}</div>{settings.onboarded&&<div className="settings-goals"><Field label="Daily calorie goal (0 to hide)"><input type="number" min="0" max="10000" value={prefs.calorieGoal} onChange={e=>a.setPrefs(p=>({...p,calorieGoal:Number(e.target.value)}))}/></Field><div className="two-fields"><Field label="Wind-down time"><input type="time" value={prefs.bedtime} onChange={e=>a.setPrefs(p=>({...p,bedtime:e.target.value}))}/></Field><Field label="Wake time"><input type="time" value={prefs.wakeTime} onChange={e=>a.setPrefs(p=>({...p,wakeTime:e.target.value}))}/></Field></div></div>}</div>{a.formError&&<p role="alert" className="form-error">{a.formError}</p>}<div className="modal-bottom"><span>{prefs.modules.length} of 7 selected</span><Button disabled={!prefs.modules.length||a.submitting} onClick={()=>void a.saveSettings()}>{a.submitting?<LoaderCircle className="spin"/>:<Check size={17}/>} {settings.onboarded?"Save my tools":"Create my day"}</Button></div></DialogContent></Dialog>
 <Dialog open={!!editor} onOpenChange={open=>{if(!open)a.setEditor(null)}}><DialogContent className="entry-dialog"><DialogHeader><DialogTitle>{editor?({task:"A little clarity.",grocery:"Add to your list.",food:"What's on your plate?",sleep:"How did you sleep?",move:"Make your movement count.",alarm:"A good start to your day.",event:"Make a little space for a plan.",reflection:"A moment to remember.",timer:"Set timer",session:"Focus session"}[editor.kind]):""}</DialogTitle><DialogDescription>{editor?.kind==="food"?"Food and portions are enough. Add nutrition estimates only if you know them.":"Make it yours. You can edit it later."}</DialogDescription></DialogHeader><form onSubmit={a.submitEntry} className="entry-form">{editor&&<>
 {!["sleep","reflection"].includes(editor.kind)&&<Field label={editor.kind==="food"?"Food and portion":editor.kind==="grocery"?"Item":"Name"}><input autoFocus required maxLength={160} value={draft.title||""} onChange={e=>field("title",e.target.value)} placeholder={editor.kind==="task"?"What's your next priority?":editor.kind==="food"?"e.g. 2 eggs and a slice of toast":""}/></Field>}
 {["task","food","sleep","move","event","reflection"].includes(editor.kind)&&<Field label={editor.kind==="sleep"?"Wake-up date":"Date"}><input required type="date" value={draft.date} onChange={e=>field("date",e.target.value)}/></Field>}
 {["task","move"].includes(editor.kind)&&<Field label="Minutes"><input required type="number" min="1" max={editor.kind==="task"?240:600} value={draft.minutes} onChange={e=>field("minutes",Number(e.target.value))}/></Field>}
 {editor.kind==="event"&&<><label className="calendar-form-check"><input type="checkbox" checked={draft.allDay} onChange={e=>field("allDay",e.target.checked)}/>All day</label>{!draft.allDay&&<div className="two-fields"><Field label="Start time"><input type="time" required value={draft.time} onChange={e=>field("time",e.target.value)}/></Field><Field label="Duration (minutes)"><input type="number" required min="1" max="1440" value={draft.minutes} onChange={e=>field("minutes",Number(e.target.value))}/></Field></div>}<Field label="Place (optional)"><input maxLength={200} value={draft.location} onChange={e=>field("location",e.target.value)}/></Field><label className="calendar-text-field">Notes (optional)<textarea maxLength={3000} rows={3} value={draft.notes} onChange={e=>field("notes",e.target.value)}/></label><p className="helper">Times use this device’s local time. Calendar plans don’t send reminders yet.</p></>}
 {editor.kind==="move"&&Array.isArray(draft.sets)&&<div className="well-space workout-editor"><h3>Your recorded sets</h3>{(draft.sets as WorkoutSet[]).map((set,index)=><fieldset key={index} className="workout-editor-set"><legend>Set {index+1}</legend><Field label="Exercise"><input required maxLength={80} value={set.exercise} onChange={e=>field("sets",draft.sets.map((s:WorkoutSet,i:number)=>i===index?{...s,exercise:e.target.value}:s))}/></Field><div className="two-fields"><Field label={set.seconds!==undefined?"Seconds":"Reps"}><input required type="number" min="1" max={set.seconds!==undefined?3600:200} value={set.seconds??set.reps} onChange={e=>field("sets",draft.sets.map((s:WorkoutSet,i:number)=>i===index?(s.seconds!==undefined?{...s,seconds:Number(e.target.value)}:{...s,reps:Number(e.target.value)}):s))}/></Field><Field label="Weight (kg)"><input required type="number" min="0" max="500" step=".25" value={set.kg} onChange={e=>field("sets",draft.sets.map((s:WorkoutSet,i:number)=>i===index?{...s,kg:Number(e.target.value)}:s))}/></Field></div></fieldset>)}</div>}
 {editor.kind==="reflection"&&<label className="calendar-text-field">What would you like to remember?<textarea autoFocus required maxLength={3000} rows={6} value={draft.text} placeholder="Something you tried, enjoyed, learned, or made a little easier…" onChange={e=>field("text",e.target.value)}/></label>}
 {editor.kind==="grocery"&&<Field label="Quantity"><input required maxLength={40} value={draft.quantity} placeholder="e.g. 2 packs" onChange={e=>field("quantity",e.target.value)}/></Field>}
 {editor.kind==="food"&&<><Field label="Meal"><Pick label="Meal" value={draft.meal} items={["Breakfast","Lunch","Dinner","Snack"]} onChange={(v:string)=>field("meal",v)}/></Field><label className="calendar-form-check"><input type="checkbox" checked={draft.nutritionKnown!==false} onChange={e=>field("nutritionKnown",e.target.checked)}/>Include nutrition estimates</label>{draft.nutritionKnown!==false&&<div className="two-fields">{[["calories","Calories (kcal)"],["protein","Protein (g)"],["carbs","Carbs (g)"],["fat","Fat (g)"]].map(([key,label])=><Field key={key} label={label}><input required type="number" min="0" max={key==="calories"?10000:1000} step="0.1" value={draft[key]} onChange={e=>field(key,Number(e.target.value))}/></Field>)}</div>}</>}
 {editor.kind==="sleep"&&<><div className="two-fields"><Field label="Fell asleep"><input required type="time" value={draft.bedtime} onChange={e=>field("bedtime",e.target.value)}/></Field><Field label="Woke up"><input required type="time" value={draft.wakeTime} onChange={e=>field("wakeTime",e.target.value)}/></Field></div><Field label="How do you feel?"><Pick label="Sleep quality" value={draft.quality} items={["Rested","Okay","Tired"]} onChange={(v:string)=>field("quality",v)}/></Field><p className="helper">{Math.floor(sleepMinutes(draft.bedtime,draft.wakeTime)/60)}h {sleepMinutes(draft.bedtime,draft.wakeTime)%60}m · Overnight sleep is calculated automatically.</p></>}
 {editor.kind==="alarm"&&<><Field label="Time"><input required type="time" value={draft.time} onChange={e=>field("time",e.target.value)}/></Field><div className="field"><span>Repeat on</span><div className="day-choices">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((name,i)=><label key={name}><Checkbox checked={draft.days?.includes(i)} onCheckedChange={checked=>field("days",checked?[...draft.days,i].sort():draft.days.filter((x:number)=>x!==i))}/>{name}</label>)}</div></div><p className="helper">No days selected means a one-time alarm at the next occurrence. Keep this app open.</p></>}
 </>}{a.formError&&<p role="alert" className="form-error">{a.formError}</p>}<Button className="full-button" type="submit" disabled={a.submitting}>{a.submitting?<LoaderCircle className="spin"/>:<Check/>}Save entry</Button></form></DialogContent></Dialog>
 <Dialog open={a.photoDialog} onOpenChange={open=>{a.setPhotoDialog(open);if(!open&&photo){URL.revokeObjectURL(photo);a.setPhoto(null)}}}><DialogContent><DialogHeader><DialogTitle>A picture of your plate.</DialogTitle><DialogDescription>Preview the photo flow. Automatic food recognition needs an AI service connected.</DialogDescription></DialogHeader><label className="photo-drop">{photo?<img src={photo} alt="Selected meal preview"/>:<><Camera size={35}/><strong>Choose a meal photo</strong><span>Stays on your device in this preview</span></>}<input type="file" accept="image/*" capture="environment" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>10*1024*1024){toast.error("Choose an image smaller than 10 MB.");return}if(photo)URL.revokeObjectURL(photo);a.setPhoto(URL.createObjectURL(file))}}/></label><p className="helper">No calorie estimate has been generated. You can enter the meal and its nutrition details yourself.</p><Button onClick={()=>{a.setPhotoDialog(false);if(photo)URL.revokeObjectURL(photo);a.setPhoto(null);a.openEditor("food")}}>Enter meal details</Button></DialogContent></Dialog>
 <Dialog open={plan!==null} onOpenChange={open=>{if(!open)a.setPlan(null)}}><DialogContent><DialogHeader><DialogTitle>{plan?.some(e=>e.kind==="grocery")?"A little prep, an easier meal.":"A simple plan for your day."}</DialogTitle><DialogDescription>Review these suggestions before adding them.</DialogDescription></DialogHeader><div className="plan-list">{plan?.length?plan.map(e=><div key={e.id}><Check size={17}/><span>{e.data.title}</span><Button variant="ghost" size="icon" aria-label={`Remove suggestion ${e.data.title}`} onClick={()=>a.setPlan(p=>p!.filter(x=>x.id!==e.id))}><X/></Button></div>):<p>You're all set. Nothing new to add.</p>}</div><Button disabled={!plan?.length||a.saving>0} onClick={async()=>{if(plan&&await a.save(plan,"Added to your day"))a.setPlan(null)}}>Add {plan?.length||0} {plan?.some(e=>e.kind==="grocery")?"ingredients":"tasks"}</Button></DialogContent></Dialog>
 <Dialog open={!!ring} onOpenChange={open=>{if(!open)a.setRing(null)}}><DialogContent><DialogHeader><div className="modal-mark"><AlarmClock/></div><DialogTitle>{ring?.title}</DialogTitle><DialogDescription>Take a moment for yourself.</DialogDescription></DialogHeader><div className="button-row">{ring?.id&&<Button variant="outline" onClick={async()=>{const e=a.entries.find(x=>x.id===ring.id);if(e&&await a.save([{...e,data:{...e.data,enabled:true,snoozeAt:Date.now()+300000}}]))a.setRing(null)}}>Snooze 5 minutes</Button>}<Button onClick={()=>a.setRing(null)}>Dismiss</Button></div></DialogContent></Dialog></>;
}
