"use client";
import {foodDetail, activityDetail} from "@/lib/food-tracking";
import {TaskWorkspace,GroceryWorkspace} from "./everyday";
import {formatDuration} from "@/lib/routines";
import {useState} from "react";
import {Moon,Footprints,Plus,CheckCheck,Camera,Utensils,AlarmClock,Volume2,Play,Pause,RotateCcw,Clock} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Switch} from "@/components/ui/switch";
import {Progress} from "@/components/ui/progress";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {today,displayTime} from "@/lib/daywell";
import type {AppState} from "./use-daywell";
import {FocusCard,FoodCard,RecipeCard,Empty,EntryActions,Field} from "./parts";
export function ModuleView({a}:{a:AppState}){
 const [timerMinutes,setTimerMinutes]=useState(25);const {sw,setSw}=a;
 const {active,settings,now,by,dayEntries}=a,tasks=dayEntries("task"),meals=dayEntries("food"),activities=dayEntries("move"),sleep=dayEntries("sleep").at(-1),movement=activities.reduce((n,e)=>n+e.data.minutes,0),focused=dayEntries("session").reduce((n,e)=>n+e.data.minutes,0);
 if(active==="focus")return <><div className="overview-grid"><FocusCard a={a}/><section className="card focus-summary"><span className="icon-box purple"><CheckCheck/></span><h2>A little progress adds up.</h2><strong>{focused}<small>min focused today</small></strong><Progress value={tasks.length?tasks.filter(e=>e.data.done).length/tasks.length*100:0}/><p>{tasks.filter(e=>e.data.done).length} of {tasks.length} priorities complete</p></section></div><TaskWorkspace a={a}/></>;
 if(active==="clock")return <Tabs defaultValue="timer"><TabsList className="clock-tabs"><TabsTrigger value="timer">Timer</TabsTrigger><TabsTrigger value="stopwatch">Stopwatch</TabsTrigger><TabsTrigger value="world">World clock</TabsTrigger></TabsList><TabsContent value="timer"><div className="overview-grid"><FocusCard a={a}/><section className="card timer-settings"><h2>Make time for something.</h2><p>Choose a length, then settle in.</p><div className="preset-times">{[5,15,25,50].map(m=><button key={m} className={a.timer.duration===m*60?"selected":""} onClick={()=>{setTimerMinutes(m);void a.resetTimer(m*60,"Timer")}}>{m} min</button>)}</div><Field label="Custom duration (minutes)"><input type="number" min="1" max="1440" value={timerMinutes} onChange={e=>setTimerMinutes(Number(e.target.value))}/></Field><Button disabled={!Number.isInteger(timerMinutes)||timerMinutes<1||timerMinutes>1440} onClick={()=>void a.resetTimer(timerMinutes*60,"Timer")}>Set timer</Button><p className="helper">Keep Daywell open for the finishing sound.</p></section></div></TabsContent><TabsContent value="stopwatch"><section className="card stopwatch"><Clock size={30}/><h2>Stay in the moment.</h2><div className="stopwatch-digits">{formatDuration(((sw.running?Math.max(0,now-sw.start):0)+sw.elapsed)/1000)}</div><div className="button-row"><Button onClick={()=>setSw(s=>s.running?{...s,elapsed:s.elapsed+Date.now()-s.start,running:false}:{...s,start:Date.now(),running:true})}>{sw.running?<Pause/>:<Play/>}{sw.running?"Pause":"Start"}</Button><Button variant="outline" onClick={()=>setSw({start:0,elapsed:0,running:false})}><RotateCcw/>Reset</Button></div></section></TabsContent><TabsContent value="world"><div className="world-grid">{[["Your time",undefined],["London","Europe/London"],["New York","America/New_York"],["Tokyo","Asia/Tokyo"]].map(([label,zone])=><section className="card" key={label}><span className="eyebrow">{label}</span><h2>{new Date(now).toLocaleTimeString("en-GB",{timeZone:zone,hour:"2-digit",minute:"2-digit",second:"2-digit"})}</h2><p>{new Date(now).toLocaleDateString("en-GB",{timeZone:zone,weekday:"long",month:"short",day:"numeric"})}</p></section>)}</div></TabsContent></Tabs>;
 if(active==="alarm")return <><div className="notice"><AlarmClock size={20}/><p>Keep Daywell open for web alarms. For a dependable wake-up alarm, also set your phone's alarm.</p><Button variant="outline" onClick={()=>{a.unlockAudio();setTimeout(()=>{a.beep();a.setRing({title:"Your alarm sounds like this."})},150)}}><Volume2/>Test sound</Button></div><div className="section-title section-gap"><h2>Your alarms</h2><Button onClick={()=>{a.unlockAudio();a.openEditor("alarm")}}><Plus/>Add alarm</Button></div><div className="alarm-grid">{by("alarm").map(e=><section className={`card alarm-card ${e.data.enabled?"":"alarm-off"}`} key={e.id}><div className="section-title"><span>{e.data.title}</span><Switch aria-label={`Enable ${e.data.title}`} checked={e.data.enabled} onCheckedChange={enabled=>{a.unlockAudio();void a.save([{...e,data:{...e.data,enabled}}])}}/></div><strong className="alarm-time">{displayTime(e.data.time)}</strong><p>{e.data.days.length?e.data.days.map((d:number)=>["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][d]).join(" · "):"One time"}</p><div className="card-foot"><span>{e.data.enabled?"Scheduled while app is open":"Paused"}</span><div><EntryActions a={a} e={e}/></div></div></section>)}</div>{!by("alarm").length&&<section className="card section-gap"><Empty icon={AlarmClock} title="Give tomorrow a good start." description="Set your first alarm and choose the days it repeats."/></section>}</>;
 if(active==="sleep")return <><div className="overview-grid"><section className="sleep-hero"><Moon size={30}/><h2>A softer landing tonight.</h2><p>Your evening rhythm</p><div className="sleep-times"><div><span>WIND DOWN</span><strong>{displayTime(settings.bedtime)}</strong></div><div><span>WAKE UP</span><strong>{displayTime(settings.wakeTime)}</strong></div></div><div className="button-row"><Button className="light-button" onClick={()=>{a.setPrefs(settings);a.setCustomize(true)}}>Adjust schedule</Button>{a.enabled("alarm")&&<Button className="ghost-light" variant="ghost" onClick={()=>{a.unlockAudio();a.openEditor("alarm")}}>Set wake alarm</Button>}</div></section><section className="card focus-summary"><span className="icon-box purple"><Moon/></span><h2>Last night's rest</h2><strong>{sleep?`${Math.floor(sleep.data.minutes/60)}h ${sleep.data.minutes%60}m`:"—"}<small>{sleep?`Feeling ${sleep.data.quality.toLowerCase()}`:"No sleep logged yet"}</small></strong><Button variant="outline" onClick={()=>a.openEditor("sleep",sleep)}><Plus/>{sleep?"Edit sleep":"Log your sleep"}</Button></section></div><section className="card section-gap"><div className="section-title"><h2>Your sleep journal</h2><Button variant="ghost" onClick={()=>a.openEditor("sleep")}><Plus/>Add a night</Button></div>{by("sleep").length?<div className="entry-list">{by("sleep").sort((x,y)=>y.data.date.localeCompare(x.data.date)).map(e=><div className="task-row" key={e.id}><span className="icon-box purple"><Moon size={19}/></span><div className="entry-main"><strong>{e.data.date} · {Math.floor(e.data.minutes/60)}h {e.data.minutes%60}m</strong><small>{displayTime(e.data.bedtime)} – {displayTime(e.data.wakeTime)} · {e.data.quality}</small></div><EntryActions a={a} e={e}/></div>)}</div>:<Empty icon={Moon} title="Notice your rhythm." description="Log bedtime, wake time and how you feel. No wearable needed."/>}</section></>;
 if(active==="grocery")return <><GroceryWorkspace a={a}/><div className="section-gap"><RecipeCard a={a}/></div></>;
 if(active==="food")return <><div className="overview-grid food-overview"><FoodCard a={a}/><section className="card photo-card"><span className="camera-icon"><Camera size={30}/></span><h2>What's on your plate?</h2><p>Show a photo or describe your meal, then check the portion before saving.</p><Button onClick={()=>window.dispatchEvent(new CustomEvent("daywell-capture",{detail:{mode:"meal"}}))}><Camera/>Tell Daywell about a meal</Button><Button variant="ghost" onClick={()=>a.openEditor("food")}>Enter details manually</Button><span className="feature-note">Your details stay editable</span></section></div><section className="card section-gap"><div className="section-title"><h2>Today's food</h2><span className="muted">{meals.length} meals logged</span></div>{meals.length?<div className="entry-list">{meals.map(e=><div className="task-row" key={e.id}><span className="icon-box peach"><Utensils size={18}/></span><div className="entry-main"><strong>{e.data.title}</strong><small>{e.data.meal} · {foodDetail(e.data)}</small></div><EntryActions a={a} e={e}/></div>)}</div>:<Empty icon={Utensils} title="Your food story starts here." description="Log your first meal. You can adjust the details any time."/>}<p className="helper">Calories are estimates. Your daily goal is editable in Customize tools.</p></section><div className="section-gap"><RecipeCard a={a}/></div></>;
 if(active==="move")return <><section className="movement-hero"><div><span className="eyebrow">A LITTLE MOVEMENT GOES A LONG WAY</span><h2>Find your own pace.</h2><p>A walk, a stretch, a workout. It all counts.</p><Button onClick={()=>a.openEditor("move")}><Plus/>Log movement</Button></div><div className="movement-total"><Footprints size={28}/><strong>{movement}</strong><span>minutes today</span></div></section><div className="movement-prompts">{[["Walk",15,"Step outside"],["Stretch",5,"Find some space"],["Workout",30,"Make time for you"]].map(([name,min,desc])=><button className="card" key={name} onClick={()=>{a.openEditor("move");a.setDraft({title:name,date:today(),minutes:min})}}><Footprints size={20}/><h3>{name}</h3><p>{min} min · {desc}</p><span>Log activity<Plus size={15}/></span></button>)}</div><section className="card section-gap"><div className="section-title"><h2>Today's movement</h2><span className="muted">Your daily activity</span></div>{activities.length?<div className="entry-list">{activities.map(e=><div className="task-row" key={e.id}><span className="icon-box mint"><Footprints size={18}/></span><div className="entry-main"><strong>{e.data.title}</strong><small>{e.data.minutes} minutes · {activityDetail(e.data)}</small></div><EntryActions a={a} e={e}/></div>)}</div>:<Empty icon={Footprints} title="Every small move counts." description="Log an activity when you're done, and see your day add up."/>}</section></>;
 return null;
}
