"use client";
import {Timer,Play,Pause,RotateCcw,Plus,Utensils,ListChecks,Pencil,Trash2,ShoppingBasket} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Checkbox} from "@/components/ui/checkbox";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {today,type Entry} from "@/lib/daywell";
import type {AppState} from "./use-daywell";
export function Field({label,children}:any){return <label className="field"><span>{label}</span>{children}</label>}
export function Pick({value,onChange,items,label}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map((x:string)=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select>}
export function Empty({icon:Icon=ListChecks,title,description}:any){return <div className="empty-priorities"><Icon size={30}/><h3>{title}</h3><p>{description}</p></div>}
export function EntryActions({a,e}:{a:AppState,e:Entry}){return <><Button variant="ghost" size="icon" aria-label={`Edit ${e.data.title||e.kind}`} onClick={()=>a.openEditor(e.kind,e)}><Pencil/></Button><Button variant="ghost" size="icon" aria-label={`Delete ${e.data.title||e.kind}`} onClick={()=>void a.remove(e)}><Trash2/></Button></>}
export function TaskRows({a,items}:{a:AppState,items:Entry[]}){return <div className="entry-list">{items.map(e=><div className="task-row" key={e.id}><Checkbox disabled={a.saving>0} aria-label={`Complete ${e.data.title}`} checked={e.data.done} onCheckedChange={done=>void a.save([{...e,data:{...e.data,done:!!done}}])}/><div className={`entry-main ${e.data.done?"complete":""}`}><strong>{e.data.title}</strong><small>{e.data.minutes} min {e.data.date!==today()?`· ${e.data.date}`:""}{!e.data.done&&e.data.date<today()&&<span className="overdue-label">Carried over</span>}</small></div>{!e.data.done&&<Button variant="ghost" size="icon" aria-label={`Focus on ${e.data.title}`} onClick={()=>void a.runTimer("Focus",e.data.minutes*60,e.data.title)}><Play/></Button>}<EntryActions a={a} e={e}/></div>)}</div>}
export function FocusCard({a}:{a:AppState}){const {timer,remaining}=a;return <section className="focus-card"><div className="card-top"><span><span className="tiny-dot"/>{timer.endAt?`${timer.mode.toUpperCase()} IN PROGRESS`:timer.mode==="Break"?"TIME TO RECHARGE":timer.mode==="Timer"?"YOUR TIME, YOUR WAY":"TIME TO FOCUS"}</span><Timer size={20}/></div><div className="focus-modes" role="group" aria-label="Timer mode">{[{label:"Focus",mode:"Focus",duration:1500},{label:"Short break",mode:"Break",duration:300},{label:"Long break",mode:"Break",duration:900}].map(p=><button key={p.label} disabled={a.saving>0} aria-pressed={timer.mode===p.mode&&timer.duration===p.duration} onClick={()=>void a.resetTimer(p.duration,p.mode)}>{p.label}</button>)}</div><h2>{timer.title}</h2><p>{timer.mode==="Break"?"Step away. Take a breath. Come back fresh.":"Give your next priority a little breathing room."}</p><div className="timer-display" aria-label={`${Math.floor(remaining/60)} minutes ${remaining%60} seconds`}>{String(Math.floor(remaining/60)).padStart(2,"0")}<span>:</span>{String(remaining%60).padStart(2,"0")}</div><div className="focus-bottom"><Button disabled={!a.loaded||a.saving>0} className="light-button" onClick={()=>timer.endAt?void a.pauseTimer():void a.runTimer(timer.mode)}>{timer.endAt?<Pause size={16}/>:<Play size={16}/>} {timer.endAt?"Pause":remaining<timer.duration&&remaining>0?"Resume":timer.mode==="Focus"?"Start focus":"Start timer"}</Button><Button disabled={a.saving>0} className="timer-reset" variant="ghost" aria-label="Reset timer" onClick={()=>void a.resetTimer()}><RotateCcw size={17}/></Button><span className="focus-hint">{timer.mode==="Focus"?"A little focus goes a long way.":"Take this time for yourself."}</span></div></section>}
export function FoodCard({a}:{a:AppState}){const meals=a.dayEntries("food"),calories=meals.reduce((n,e)=>n+e.data.calories,0);return <section className="card nutrition-card"><div className="section-title"><h2>Daily fuel</h2><span className="icon-box peach"><Utensils size={20}/></span></div><div className="fuel-circle" style={{background:`conic-gradient(#e9a571 ${Math.min(1,calories/(a.settings.calorieGoal||1))*360}deg,#f9eee4 0deg)`}}><div><strong>{Math.round(calories).toLocaleString()}</strong><small>{a.settings.calorieGoal?`of ${a.settings.calorieGoal.toLocaleString()} kcal`:"kcal logged"}</small></div></div><div className="macros">{["protein","carbs","fat"].map((key,i)=><div key={key}><span className={`macro-line macro-${i}`}/><strong>{Math.round(meals.reduce((n,e)=>n+e.data[key],0))}g</strong><small>{key}</small></div>)}</div><Button variant="outline" onClick={()=>a.openEditor("food")}><Plus/>Log a meal</Button><button className="food-capture-link" onClick={()=>window.dispatchEvent(new CustomEvent("daywell-capture",{detail:{mode:"meal"}}))}>Try photo or voice</button></section>}
export function RecipeCard({a}:{a:AppState}){return <section className="card recipe-card"><img src="/grain-bowl.jpg" alt="Salmon and quinoa bowl with colourful vegetables"/><div><div className="eyebrow">A LITTLE MEAL INSPIRATION</div><h2>Colourful salmon bowl</h2><p>Quinoa, crunchy vegetables and a little mango. Make it your own.</p><div className="recipe-actions">{a.enabled("grocery")&&<Button variant="outline" onClick={()=>a.setPlan(["Salmon fillet","Quinoa","Edamame","Carrot","Red cabbage","Mango"].filter(title=>!a.by("grocery").some(e=>e.data.title.toLowerCase()===title.toLowerCase()&&!e.data.done)).map(title=>({id:crypto.randomUUID(),kind:"grocery",data:{title,quantity:"1 portion",done:false}})))}><ShoppingBasket/>Add ingredients</Button>}{a.enabled("food")&&<Button variant="ghost" onClick={()=>{a.openEditor("food");a.setDraft({title:"Salmon and quinoa bowl",date:today(),calories:620,protein:40,carbs:52,fat:28,meal:"Lunch"})}}>Log this meal</Button>}</div><small>Example portion: approximately 620 kcal. Adjust to your ingredients.</small></div></section>}
