"use client";
import {useEffect,useRef,useState} from "react";
import {useFood} from "./use-food";
import {starterModules} from "@/lib/onboarding";
import {stampCompletions,type CalendarArea} from "@/lib/calendar";
import {timerTitle} from "@/lib/routines";
import {toast} from "sonner";
import {defaults,today,sleepMinutes,type Settings,type Entry,type Kind} from "@/lib/daywell";
export const initialTimer={title:"One thing at a time.",duration:1500,remaining:1500,endAt:null,mode:"Focus"};
export function useDaywell(showWelcome=false,initialView="today"){
 const [welcome,setWelcome]=useState(false);
 const [calendarView,setCalendarView]=useState<"plan"|"history">("plan");
 const [calendarArea,setCalendarArea]=useState<CalendarArea>("all");
 const [sw,setSw]=useState({start:0,elapsed:0,running:false});
 const [syncError,setSyncError]=useState("");
 const [settings,setSettings]=useState<Settings>(defaults),[entries,setEntries]=useState<Entry[]>([]),[active,setActive]=useState(initialView),[restReturn,setRestReturn]=useState(false),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(""),[saving,setSaving]=useState(0),[now,setNow]=useState(Date.now());
 const [recoveryScope,setRecoveryScope]=useState<string|null>(null);
 const food=useFood((active==="eat"||active==="calendar")&&loaded,load,recoveryScope);
 useEffect(()=>{window.scrollTo({top:0,behavior:"instant"})},[active]);
 const [customize,setCustomize]=useState(false),[prefs,setPrefs]=useState<Settings>(defaults),[editor,setEditor]=useState<{kind:Kind,id:string}|null>(null),[draft,setDraft]=useState<any>({}),[submitting,setSubmitting]=useState(false),[formError,setFormError]=useState(""),[photo,setPhoto]=useState<string|null>(null),[photoDialog,setPhotoDialog]=useState(false),[plan,setPlan]=useState<Entry[]|null>(null),[ring,setRing]=useState<{title:string,id?:string}|null>(null);
 const current=useRef({settings,entries});current.current={settings,entries};const audio=useRef<AudioContext|null>(null),completed=useRef<number|null>(null),alarmFired=useRef(new Set<string>()),prevTick=useRef(Date.now());
 async function load(){setLoadError("");try{const r=await fetch("/api/state",{cache:"no-store"});const data:any=await r.json();if(!r.ok){if(r.status===401||r.status===403){setLoaded(false);setRecoveryScope(null)}throw Error(data.error)}setRecoveryScope(data.recoveryScope);const loadedSettings={...defaults,...data.settings};setSettings(loadedSettings);setPrefs(loadedSettings.onboarded?loadedSettings:{...loadedSettings,modules:[...starterModules]});setEntries(data.entries);setLoaded(true);if(!loadedSettings.onboarded||showWelcome)setWelcome(true)}catch(e:any){setLoadError(e.message||"Couldn't load your day.")}}
 useEffect(()=>{void load();const id=setInterval(()=>setNow(Date.now()),500);return ()=>clearInterval(id)},[]);
 async function request(body:any){setSaving(n=>n+1);try{const r=await fetch("/api/state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data:any=await r.json();if(!r.ok)throw Error(data.error);setSyncError("");return data}catch(e){setSyncError(e instanceof Error?e.message:"Could not save");throw e}finally{setSaving(n=>n-1)}}
 async function put(items:Entry[]){const result=await request({action:"upsert",entries:stampCompletions(items,current.current.entries,today(),new Date().toISOString())});setEntries(prev=>[...prev.filter(e=>!items.some(x=>x.id===e.id)),...result.entries]);if(items.some(e=>e.kind==="grocery"))await food.refresh();return result.entries as Entry[]}
 async function hostChange(items:Entry[],removeIds:string[]=[]){const result=await request({action:"host-change",entries:items,removeIds});setEntries(prev=>[...prev.filter(e=>!removeIds.includes(e.id)&&!items.some(x=>x.id===e.id)),...result.entries]);if(items.some(e=>e.kind==="grocery")||removeIds.length)await food.refresh();return result.entries as Entry[]}
 async function save(items:Entry[],message?:string){try{const result=await put(items);if(message)toast.success(message);return result}catch(e:any){toast.error(e.message);return null}}
 async function remove(e:Entry){try{await request({action:"remove",id:e.id});setEntries(p=>p.filter(x=>x.id!==e.id));if(e.kind==="grocery")await food.refresh();toast("Entry removed",{action:{label:"Undo",onClick:()=>void hostChange([e]).catch(err=>toast.error(err instanceof Error?err.message:"Could not restore entry"))}})}catch(err:any){toast.error(err.message)}}
 async function saveSleepTimes(bedtime:string,wakeTime:string){try{const result=await request({action:"settings",data:{...settings,bedtime,wakeTime}});setSettings(result.data);toast.success("Times saved");return ""}catch(e){return e instanceof Error&&e.message?e.message:"Couldn’t save your times. Please try again."}}
 async function saveSettings(){setSubmitting(true);setFormError("");try{const result=await request({action:"settings",data:{...prefs,name:prefs.name.trim()||"You",onboarded:true,...(welcome?{guideDismissed:false}:{})}});setSettings(result.data);if(!["today","calendar","explore","relax","eat","move","sleep"].includes(active)&&!result.data.modules.includes(active))setActive("today");setCustomize(false);setWelcome(false);if(welcome)setActive("today");toast.success("Your space is ready")}catch(e:any){setFormError(e.message)}finally{setSubmitting(false)}}
 async function dismissGuide(){try{const result=await request({action:"settings",data:{...settings,guideDismissed:true}});setSettings(result.data);setPrefs(result.data)}catch(e){toast.error(e instanceof Error?e.message:"Could not save your preference")}}
 function openEditor(kind:Kind,entry?:Entry){setFormError("");setEditor({kind,id:entry?.id||crypto.randomUUID()});setDraft(entry?.data||({task:{title:"",date:today(),done:false,minutes:25},grocery:{title:"",quantity:"1",done:false},food:{title:"",date:today(),calories:0,protein:0,carbs:0,fat:0,meal:"Lunch",nutritionKnown:false,macrosKnown:false,foodStatus:"eaten",portions:1},sleep:{date:today(),bedtime:settings.bedtime,wakeTime:settings.wakeTime,minutes:sleepMinutes(settings.bedtime,settings.wakeTime),quality:"Okay"},move:{title:"Walk",date:today(),minutes:15},alarm:{title:"Morning alarm",time:settings.wakeTime,enabled:true,days:[1,2,3,4,5]},event:{title:"",date:today(),allDay:false,time:"09:00",minutes:60,location:"",notes:"",done:false},reflection:{date:today(),text:""},timer:initialTimer,session:{title:"",date:today(),minutes:25}}[kind]));}
 async function submitEntry(ev:React.FormEvent){ev.preventDefault();if(!editor)return;setFormError("");const data={...draft};if(editor.kind==="sleep"){data.minutes=sleepMinutes(data.bedtime,data.wakeTime);if(data.minutes<1||data.minutes>960){setFormError("Choose a sleep period between 1 minute and 16 hours.");return}}setSubmitting(true);try{await put([{...editor,data}]);setEditor(null);toast.success("Saved to your day")}catch(e:any){setFormError(e.message)}finally{setSubmitting(false)}}
 function unlockAudio(){try{if(!audio.current)audio.current=new AudioContext();void audio.current.resume()}catch{}}
 function beep(){try{const ctx=audio.current;if(!ctx)return;[0,.25,.5].forEach(offset=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=660;gain.gain.setValueAtTime(.12,ctx.currentTime+offset);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+offset+.18);osc.start(ctx.currentTime+offset);osc.stop(ctx.currentTime+offset+.2)})}catch{}}
 const enabled=(id:string)=>settings.modules.includes(id as any),by=(kind:Kind)=>entries.filter(e=>e.kind===kind),dayEntries=(kind:Kind)=>by(kind).filter(e=>e.data.date===today());const timer=by("timer")[0]?.data||initialTimer,remaining=timer.endAt?Math.min(timer.duration,Math.max(0,Math.ceil((timer.endAt-now)/1000))):timer.remaining;
 async function runTimer(mode="Focus",duration?:number,title?:string){unlockAudio();const seconds=duration??(remaining||timer.duration);await save([{id:"timer",kind:"timer",data:{...timer,companion:duration===undefined&&mode===timer.mode?(timer.companion||(mode==="Focus"?"pip":"tock")):(mode==="Focus"?"pip":"tock"),startedAt:duration||!timer.startedAt||remaining===0?Date.now():timer.startedAt,title:title||timer.title,mode,duration:duration??timer.duration,remaining:seconds,endAt:Date.now()+seconds*1000}}]);}
 async function pauseTimer(){await save([{id:"timer",kind:"timer",data:{...timer,remaining,endAt:null}}])}
 async function resetTimer(duration=timer.duration,mode=timer.mode){await save([{id:"timer",kind:"timer",data:{...timer,companion:mode==="Focus"?"pip":"tock",startedAt:undefined,title:timerTitle(mode),duration,remaining:duration,endAt:null,mode}}])}
 useEffect(()=>{if(!loaded)return;const t=current.current.entries.find(e=>e.kind==="timer")?.data;if(t?.endAt&&now>=t.endAt&&completed.current!==t.endAt){completed.current=t.endAt;const items:Entry[]=[{id:"timer",kind:"timer",data:{...t,endAt:null,remaining:0}}];if(t.mode==="Focus")items.push({id:`session-${t.endAt}`,kind:"session",data:{title:t.title,date:today(t.endAt),minutes:Math.round(t.duration/60)}});void save(items).then(result=>{if(!result)completed.current=null});if(t.companion!=="luma"){setRing({title:t.mode==="Break"?"Ready for a fresh start?":"Time for a little breathing room."});beep()}}
 const day=today(),d=new Date(now);current.current.entries.filter(e=>e.kind==="alarm"&&e.data.enabled&&current.current.settings.modules.includes("alarm")).forEach(e=>{const a=e.data,[h,m]=a.time.split(":").map(Number),due=new Date(d.getFullYear(),d.getMonth(),d.getDate(),h,m).getTime(),snooze=a.snoozeAt&&now>=a.snoozeAt&&prevTick.current<a.snoozeAt,regular=now>=due&&prevTick.current<due&&(!a.days.length||a.days.includes(d.getDay())),key=snooze?`${e.id}-${a.snoozeAt}`:`${e.id}-${day}`;if((snooze||regular)&&!alarmFired.current.has(key)&&a.lastFired!==key){alarmFired.current.add(key);setRing({title:a.title,id:e.id});beep();void save([{...e,data:{...a,lastFired:key,snoozeAt:null,enabled:!!a.days.length}}])}});prevTick.current=now;
 },[now,loaded]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:"get_daywell_summary",description:"Read Daywell's enabled modules and today's tasks. Does not change data.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:any){if(!input||Object.keys(input).length)throw Error("Expected an empty object");const s=current.current;return {modules:s.settings.modules,tasks:s.entries.filter(e=>e.kind==="task"&&e.data.date===today()).map(e=>({id:e.id,...e.data}))}}},{signal:life.signal})).catch(()=>{});Promise.resolve(context.registerTool({name:"add_daywell_tasks",description:"Create and save one to ten tasks for today in Daywell. Updates the visible task list.",inputSchema:{type:"object",properties:{titles:{type:"array",minItems:1,maxItems:10,items:{type:"string",minLength:1,maxLength:160}}},required:["titles"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:any){if(!input||Object.keys(input).some(k=>k!=="titles")||!Array.isArray(input.titles)||input.titles.length<1||input.titles.length>10||input.titles.some((x:any)=>typeof x!=="string"||!x.trim()||x.length>160))throw Error("Provide 1–10 nonempty task titles");if(!current.current.settings.modules.includes("focus"))throw Error("Enable Productivity first");const items:Entry[]=input.titles.map((title:string)=>({id:crypto.randomUUID(),kind:"task",data:{title:title.trim(),date:today(),done:false,minutes:25}}));await put(items);return {created:items.map(x=>({id:x.id,title:x.data.title}))}}},{signal:life.signal})).catch(()=>{});return ()=>life.abort()},[]);
 return {food,calendarView,setCalendarView,calendarArea,setCalendarArea,welcome,setWelcome,dismissGuide,sw,setSw,syncError,settings,entries,active,setActive:(view:string)=>{setRestReturn(false);if(view==="grocery"){food.setView("shopping");setActive("eat")}else setActive(view)},restReturn,openRest:()=>{setRestReturn(true);setActive("relax")},saveSleepTimes,loaded,loadError,saving,now,customize,setCustomize,prefs,setPrefs,editor,setEditor,draft,setDraft,submitting,formError,setFormError,photo,setPhoto,photoDialog,setPhotoDialog,plan,setPlan,ring,setRing,load,save,hostChange,remove,saveSettings,openEditor,submitEntry,unlockAudio,beep,enabled,by,dayEntries,timer,remaining,runTimer,pauseTimer,resetTimer};
}
export type AppState=ReturnType<typeof useDaywell>;

