import type { CompanionId } from './companions.ts';

export const audioCategories = [
  { id: 'relax', label: 'A little calm' }, { id: 'sleep', label: 'Wind down' },
  { id: 'move', label: 'Get moving' }, { id: 'eat', label: 'Time to eat' },
  { id: 'focus', label: 'Find my focus' }, { id: 'progress', label: 'Look back' },
  { id: 'everyday', label: 'Everyday company' },
] as const;
export type AudioCategory = typeof audioCategories[number]['id'];
export type AudioResponse = { id: string; groupId: string; category: AudioCategory; title: string; companion: CompanionId; text: string };
export type AudioGroup = { id: string; category: AudioCategory; title: string; companion: CompanionId; responses: AudioResponse[] };
function group(id: string, category: AudioCategory, title: string, companion: CompanionId, lines: string[]): AudioGroup {
  return { id, category, title, companion, responses: lines.map((text, index) => ({ id: `${id}-${String(index + 1).padStart(2, '0')}`, groupId: id, category, title, companion, text })) };
}

// Ten independently usable, authored variations for each of fifty situations.
// These are invitations, never claims about a user's health or unsaved actions.
export const audioGroups: AudioGroup[] = [
  group('relax-arrive', 'relax', 'A place to land', 'luma', [
    'You can pause here. Find a comfortable place, and let the next thing wait for a moment.',
    'There is nothing to finish in this little corner. Just settle in at your own pace.',
    'For a moment, you do not have to choose what comes next. Let yourself arrive.',
    'Take the space you need. You can listen, look around, or simply sit quietly.',
    'You have found a little pause in the day. There is no right way to spend it.',
    'Let this be a small landing place. The rest of the day can wait outside for a moment.',
    'You do not need a good reason to rest. A comfortable seat is enough to begin.',
    'Stay for one thought, or stay a little longer. You decide what feels useful.',
    'Here is a little room to slow down. No score, no catching up, no instructions to complete.',
    'We can leave a little silence around this moment. You do not have to fill it.',
  ]),
  group('relax-scroll', 'relax', 'Step away from the feed', 'luma', [
    'The next post can wait. If you like, set your phone down after this and look around your room.',
    'You noticed that you want a break from scrolling. That is enough for a new choice right now.',
    'You can leave the feed unfinished. There is no last post you need to reach.',
    'Try giving your eyes one ordinary thing to rest on, away from the screen.',
    'A pause does not have to become a productive activity. You can simply stop for a while.',
    'If it helps, move the phone a little further away. Make this next moment easier to choose.',
    'You do not have to make up for the time you spent scrolling. Start with where you are.',
    'Let the stream of other people’s updates carry on without you for a moment.',
    'Pick something small beyond the screen: a window, a cushion, the light on a wall.',
    'When this clip ends, you can close your eyes if comfortable, or leave the screen and keep them open.',
  ]),
  group('relax-overwhelmed', 'relax', 'When everything feels like a lot', 'luma', [
    'You do not have to untangle everything at once. Choose one small thing that would make this moment easier.',
    'If decisions feel heavy, make the next choice smaller. Sitting comfortably can be the whole plan for now.',
    'Let the whole list stay a list. You only need to meet this next moment.',
    'You can put a few things down without deciding when to pick them up again.',
    'Try naming what feels most immediate. You do not need to solve it while you name it.',
    'A busy mind can have a quiet moment too. Nothing here asks you to clear every thought.',
    'You can lower the volume around you, if that feels helpful. One less input may be enough for now.',
    'There is room for a smaller version of today. Keep what matters most, and reconsider the rest later.',
    'If you need company beyond this recording, you can reach out to someone you trust.',
    'You are allowed to take the next step slowly. It does not have to explain the whole journey.',
  ]),
  group('relax-ground', 'relax', 'Notice the room', 'luma', [
    'Notice one colour near you. Let your eyes stay with it for a comfortable moment.',
    'Find the place where your body meets the chair or floor. Notice that contact, without changing anything.',
    'Listen for a sound nearby. You do not have to decide whether you like it.',
    'Look for something with a soft edge or a familiar shape. Let that be your focus for a moment.',
    'If it feels comfortable, notice the texture of your sleeve or a cushion beside you.',
    'Let your attention visit your hands. Notice where they are resting.',
    'Look around and find something ordinary that you had not noticed today.',
    'Notice the light in this space. It might be bright, dim, warm, or somewhere in between.',
    'You can keep your eyes open. Choose one steady point in the room to return to.',
    'Bring your attention back to where you are sitting. There is no need to hold it there perfectly.',
  ]),
  group('relax-breath', 'relax', 'An easy breath', 'luma', [
    'If noticing your breathing feels comfortable, let one breath come and go in its own time.',
    'There is no count to keep. Let your breathing find the pace that feels natural to you.',
    'You do not need a deeper breath. Simply notice the one that is already happening, if that suits you.',
    'Let the next breath be ordinary. You can return your attention to the room whenever you prefer.',
    'If breath focus is not helpful today, leave it alone. Listening to a nearby sound is another option.',
    'Nothing to hold, nothing to force. Let a comfortable breath pass, then take your time.',
    'You can rest a hand somewhere comfortable and notice the gentle movement of breathing.',
    'Follow one easy breath only if you want to. There is no exercise you need to complete.',
    'When your attention wanders, it has not gone wrong. Come back to a sound, a shape, or a comfortable breath.',
    'Let breathing happen in the background. You can simply be here without managing it.',
  ]),
  group('relax-unclench', 'relax', 'Find a softer position', 'luma', [
    'If it feels comfortable, let your shoulders settle into a position that takes a little less effort.',
    'Notice whether your hands are gripping anything. You can loosen that grip if you would like.',
    'Give your jaw a comfortable resting place. No stretching or forcing is needed.',
    'You can adjust the cushion, shift your feet, or move the screen. Comfort is worth a small change.',
    'Let the chair do a little more of the holding, if that feels right for your body.',
    'Try finding a position you do not have to work so hard to keep.',
    'You can change position during a pause. Stillness is an option, not a requirement.',
    'Notice one place that could use a little support. A pillow or a different seat might help.',
    'Your body does not have to look relaxed. Choose a position that feels comfortable to you.',
    'Let your hands rest for a moment. There is nothing they need to carry in this clip.',
  ]),
  group('relax-thoughts', 'relax', 'When thoughts keep arriving', 'luma', [
    'A thought can be here without becoming a task. You can notice it and leave the next step for later.',
    'You do not have to empty your mind to take a break. Thoughts can come along quietly.',
    'If something needs remembering, a short note can hold it while you pause.',
    'There is no need to finish the conversation in your head right now.',
    'Let your attention return to one thing you can see. You can do that as often as you need.',
    'A busy thought does not mean you are doing rest badly. There is no test here.',
    'You can notice that your mind has wandered without telling yourself off for it.',
    'If a thought keeps returning, you might simply name it: planning, remembering, or wondering.',
    'You can leave a question unanswered for this moment. The pause does not need an explanation.',
    'Let a sound in the room share your attention with your thoughts. There is room for both.',
  ]),
  group('relax-company', 'relax', 'Quiet company', 'luma', [
    'Here is a gentle voice for a moment. After this, there can be as much silence as you like.',
    'Luma can keep you company on the screen while you take your time.',
    'You do not have to say anything back. This little pause asks nothing of you.',
    'A familiar corner, a soft little mascot, and a moment without a new demand.',
    'You can let this be simple. Just a voice, a comfortable place, and some room to be.',
    'There is no conversation you need to keep going. Listen once, then choose what feels right.',
    'If quiet company is what you wanted, you can stop choosing clips and rest here for a while.',
    'You are welcome to stay without doing anything with this moment.',
    'Let this little recording be a kind interruption in your day.',
    'You can listen again, or let the room take over. Both are welcome.',
  ]),
  group('relax-pause', 'relax', 'A pause between things', 'luma', [
    'Before the next task, let there be a small gap. You do not have to carry the same pace into everything.',
    'One thing has your attention next. For this moment, you can let your attention rest.',
    'If you have been sitting in the same position, choose a comfortable adjustment before you continue.',
    'A break can be short and still be worth taking. You decide when it ends.',
    'You can finish a pause without proving that it helped. Taking it was enough.',
    'Let the previous task have an ending, even if it is only closing a tab or setting something down.',
    'Give yourself a moment before saying yes to the next thing.',
    'You can step away from the work without turning the break into another project.',
    'Choose one small comfort for this gap: a different seat, a quiet room, or a look outside.',
    'There is no need to rush the transition. Let your next step begin when you are ready.',
  ]),
  group('relax-return', 'relax', 'Return at your pace', 'luma', [
    'When you are ready, choose one gentle next step. You can take the quiet with you.',
    'You can stay a little longer. Leaving this pause is your choice.',
    'Look around once before returning to your day. Let the room come back into focus.',
    'Your next step can be small. A glass of water, a message, or opening one useful thing.',
    'There is no need to catch up with the whole day as you leave this moment.',
    'If you are ready to continue, decide what deserves your attention first.',
    'You can end the recording and keep resting. The screen does not need to stay open.',
    'Take a moment to notice what you need next, without making it a long list.',
    'Let the return be unhurried. You can begin with the easiest part.',
    'This quiet corner will be here when you choose to visit again.',
  ]),
  group('sleep-begin', 'sleep', 'Leave the day here', 'luma', [
    'You can begin winding down before everything is finished. Some things can belong to tomorrow.',
    'Let the evening become a little simpler. Choose one thing you can put away for tonight.',
    'There is no need to produce a perfect bedtime. A small familiar routine can be enough to start.',
    'You can set aside the day without deciding how you feel about all of it.',
    'If it suits your evening, choose a quieter activity and let the pace soften.',
    'Take a moment to make your resting place comfortable. You know what feels familiar to you.',
    'Let this be an invitation to wind down, not another deadline to meet.',
    'You do not have to earn the end of the day. You can start settling whenever you are ready.',
    'Choose a gentle ending to this part of the evening. One small ritual will do.',
    'For now, you can leave tomorrow’s whole shape undecided.',
  ]),
  group('sleep-phone', 'sleep', 'Put the screen to bed', 'luma', [
    'If you are finished with the screen, you can put it down after this recording.',
    'You can leave the messages for a time when you want to meet them. Choose what is practical for you tonight.',
    'There does not have to be one more video. You can choose an ending here.',
    'If it helps, place the phone where it is less easy to reach while you settle.',
    'You can turn down the screen brightness for comfort, then leave the rest of the app for tomorrow.',
    'A familiar piece of audio can be enough company. You do not need to keep looking at the screen.',
    'You can close this page when you want to. There is nothing here you need to watch until the end.',
    'Let the scrolling stop at an ordinary moment. It does not need a special final post.',
    'If your phone needs to stay nearby, you can still choose to turn the screen away.',
    'Choose one last useful thing to do on the phone, if needed, and let that be the stopping point.',
  ]),
  group('sleep-room', 'sleep', 'Make a comfortable corner', 'luma', [
    'Notice whether the light feels comfortable. You can change it if that is easy to do.',
    'Arrange the pillow or blanket in a way that suits you. Small comforts are allowed to matter.',
    'You can keep a familiar sound nearby, or choose quiet. There is no single right atmosphere.',
    'Let your resting place feel like somewhere you can stop arranging things for a while.',
    'If something is uncomfortable, you can adjust it. You do not need to stay still for this recording.',
    'Choose the light level that feels comfortable and practical for your room tonight.',
    'You might put tomorrow’s first useful item somewhere easy to find, then leave the rest.',
    'Let your hands settle where they feel comfortable. The bed or chair can do some of the holding.',
    'There is no special position to get right. Find the one that asks less of you.',
    'You can make this space a little quieter without making it perfect.',
  ]),
  group('sleep-thoughts', 'sleep', 'Put a thought on paper', 'luma', [
    'If tomorrow keeps asking for attention, write one short reminder and let the note hold it for now.',
    'You do not have to solve a whole problem at bedtime. You can choose a time to revisit it.',
    'A thought can pass through the evening without becoming tonight’s project.',
    'If writing helps, keep it brief. A few words can be enough to remember the important part.',
    'Let tomorrow have a place on a page, rather than asking yourself to keep rehearsing it.',
    'You can notice a planning thought and return to the room without arguing with it.',
    'There is room for unfinished thoughts at the end of a day.',
    'If a worry needs another person’s help, you can make a note of who you might speak with.',
    'You can leave a decision for a time when you feel more ready to make it.',
    'Tonight does not have to contain every answer. A reminder for later may be enough.',
  ]),
  group('sleep-settle', 'sleep', 'Settle without trying', 'luma', [
    'You do not have to make sleep happen for this moment to count as rest.',
    'Let your body choose a comfortable position. There is nothing in this clip to keep up with.',
    'You can listen without concentrating on every word. It is fine to let the voice fade into the background.',
    'There is no finish line in this recording. Just a little space to settle.',
    'If closing your eyes feels comfortable, you can. Keeping them open is fine too.',
    'Let the next few moments be ordinary. No special breathing, no effort to feel a certain way.',
    'You can stop checking whether you are doing this correctly. There is no score for settling.',
    'Notice something comfortable, however small, and let that be enough for now.',
    'If you need to shift position, take your time. Rest does not require perfect stillness.',
    'Let the recording end without choosing another thing straight away.',
  ]),
  group('sleep-awake', 'sleep', 'Awake in the night', 'luma', [
    'Being awake can feel frustrating. You do not have to turn this moment into a judgement about tomorrow.',
    'There is no need to keep checking the time while this little recording plays.',
    'If it feels useful, choose something quiet and familiar while you decide what you need.',
    'Let this moment be separate from predictions about the whole next day.',
    'You can make yourself comfortable without trying to force a particular result.',
    'If sound is irritating right now, you can stop the clip and choose silence.',
    'There is nothing you need to achieve by the end of this recording.',
    'You can let the room be simple: one familiar sound, one comfortable place, one moment at a time.',
    'If sleep difficulties keep troubling you, a healthcare professional can help you explore them.',
    'For now, meet the moment you are in. Tomorrow does not need a verdict tonight.',
  ]),
  group('sleep-reflect', 'sleep', 'A gentle evening reflection', 'luma', [
    'Was there one small moment today that you would like to remember? It does not have to be an achievement.',
    'You can name one thing that felt difficult without making the whole day a difficult day.',
    'Think of a moment when you met a need, however quietly. You can let that matter.',
    'If reflection feels like more work, you can skip it tonight.',
    'You might remember a kind word, a useful pause, or something you noticed outside.',
    'What would you like to carry into tomorrow, and what can stay with today?',
    'A day can hold both effort and unfinished things. You do not have to choose only one story about it.',
    'You can end with one sentence rather than a full account of the day.',
    'Is there a small kindness you could offer yourself before the evening ends?',
    'Let the reflection be brief and gentle. You can close it whenever you have had enough.',
  ]),
  group('sleep-goodnight', 'sleep', 'A soft goodnight', 'luma', [
    'That is all from this little voice for now. You can let the room become quiet.',
    'Goodnight from Daywell. Leave the next thing for whenever you are ready to meet it.',
    'You can put the screen away and let your own evening continue.',
    'Nothing else is required here tonight. Take the quiet you need.',
    'Luma can stay a little picture on the screen, or you can close the app. Either way, the clip is finished.',
    'Let this be a gentle ending, with no new instruction waiting after it.',
    'You have permission to leave this moment unfinished too. Rest in whatever way suits you.',
    'The words can stop now. There is room for your own quiet.',
    'Goodnight. There is no need to reply, choose a score, or record anything.',
    'Take your time settling. Daywell will be here when you choose to return.',
  ]),
  group('move-begin', 'move', 'Choose a small start', 'bounce', [
    'Choose a little movement that suits your body today. It can be much smaller than a full workout.',
    'A familiar, comfortable movement is a good place to begin. You set the pace.',
    'You do not need a dramatic start. Make enough space to move comfortably, then choose one thing.',
    'Before you begin, check that your space and equipment are ready for what you have chosen.',
    'You can choose movement because it feels useful, without making it a punishment for anything.',
    'A short session can stand on its own. It does not need to become a longer one.',
    'Start with something you already know how to do comfortably. New movements can wait for suitable guidance.',
    'There is room for a gentle version of your plan today.',
    'Your first step can be getting ready. Choose a comfortable place and something familiar to begin with.',
    'If movement is not right for you today, you can choose rest. The plan is allowed to change.',
  ]),
  group('move-pace', 'move', 'At your pace', 'bounce', [
    'You can slow down without ending the session. Your pace belongs to you.',
    'Keep your attention on how the movement feels, rather than how it might look to someone else.',
    'There is no need to match the pace of this voice. Move in the way that suits you.',
    'A comfortable, familiar pace is enough. You can adjust it as you go.',
    'If the effort feels wrong for you, pause and reconsider the next step.',
    'You can make a movement smaller or choose a familiar alternative that feels comfortable.',
    'There is no prize for rushing through the part you are doing now.',
    'Let a steady pace matter more than finishing quickly.',
    'You can check in with yourself without comparing today with another day.',
    'Choose the version you can do comfortably. Making an adjustment is part of looking after yourself.',
  ]),
  group('move-rest', 'move', 'Take a rest between efforts', 'bounce', [
    'A rest belongs in the session too. Take the time you need before deciding whether to continue.',
    'Set the equipment down safely, if you are using any, and give yourself a comfortable pause.',
    'You do not need to fill every gap with another exercise.',
    'Let this be a pause without a challenge hidden inside it.',
    'You can take longer than you planned to rest. Your next move can wait.',
    'Check whether continuing feels right today. Stopping is one of your options.',
    'If you would like a drink, take a moment for that. There is no need to hurry back.',
    'A break does not erase the movement you have already chosen to do.',
    'There is no instruction to push through pain here. Stop if something hurts or feels concerning.',
    'Use this gap to get comfortable again before choosing what comes next.',
  ]),
  group('move-walk', 'move', 'A little walk or roll', 'bounce', [
    'Choose a route and distance that suit you today. A short familiar loop is a complete option.',
    'If you go outside, keep your attention on your surroundings. This recording can wait when you need to listen.',
    'You can turn back whenever you choose. There is no distance you owe the app.',
    'A few comfortable minutes of moving around can be the whole plan.',
    'You might notice one detail along your route: a colour, a sound, or the shape of a tree.',
    'Choose somewhere practical and comfortable for the way you move.',
    'If going outside is not possible, you can choose another familiar movement or a pause indoors.',
    'You do not have to make the outing faster or longer to make it worth doing.',
    'Let the route fit your energy and circumstances, rather than forcing yourself to fit a target.',
    'When you return, you can decide whether to record the outing. It counts as an experience either way.',
  ]),
  group('move-strength', 'move', 'Before a strength session', 'bounce', [
    'Use a familiar plan and equipment you know how to handle. Ask a qualified trainer when you need help with technique.',
    'Choose a manageable version of the session. You do not need a personal record today.',
    'Take a moment to check the space around you before lifting or moving equipment.',
    'You can record the exercises and loads you choose, so there is less to remember next time.',
    'Give each movement your attention. A slower setup can be a useful part of the session.',
    'You can stop a set when you need to. A number on the plan is not an instruction to ignore discomfort.',
    'Let your current ability guide today’s choices. Someone else’s routine does not have to be yours.',
    'Keep your equipment and water within practical reach before you begin.',
    'If you are unsure about an exercise, get suitable guidance before trying to follow it from a short recording.',
    'Choose one clear intention for the session, such as practising a familiar movement carefully.',
  ]),
  group('move-adapt', 'move', 'Adjust the plan', 'bounce', [
    'A shorter session can be a thoughtful choice. You can change the plan without calling it a failure.',
    'You can choose a seated, standing, or other familiar option that suits your mobility.',
    'Today’s energy does not need to match yesterday’s. Make today’s plan for today.',
    'If the space is busy or uncomfortable, you can choose a different place or another time.',
    'You can leave out an exercise that is not right for you. The app does not need every box filled.',
    'A useful adjustment might be less time, a familiar alternative, or a rest day.',
    'Your circumstances are part of the plan. Work with what is possible right now.',
    'If you need support or advice for an injury or health condition, a qualified professional can guide your choices.',
    'You do not have to compensate tomorrow for choosing less today.',
    'Changing the plan can be a way of paying attention to yourself.',
  ]),
  group('move-finish', 'move', 'Bring movement to a close', 'bounce', [
    'If you are finishing, bring the session to a comfortable close using your usual routine.',
    'Take a moment before rushing to the next thing. You can let the session have an ending.',
    'Put any equipment away safely when you are ready. The next task can wait a moment.',
    'You can acknowledge the time you chose for movement without rating how impressive it was.',
    'Notice what you would like to remember for next time, if anything.',
    'Finishing sooner than planned is still a decision you are allowed to make.',
    'Let the session end without adding one more challenge just because it is available.',
    'If a short note would help, record what you did and how it felt in your own words.',
    'There is room to feel pleased, tired, neutral, or a mixture. No particular reaction is required.',
    'Your movement time can be complete now. Choose what you need next.',
  ]),
  group('move-return', 'move', 'Come back after a gap', 'bounce', [
    'You do not need to repay the days you missed. Choose a manageable place to begin again.',
    'A return can be gentle. Start with something familiar that suits how you feel today.',
    'There is no catch-up session waiting here. Today can have its own small plan.',
    'You are allowed to be a beginner again at something you have done before.',
    'Let the first session back be about finding a comfortable starting point.',
    'You can leave comparison with your old routine for another time.',
    'A gap can happen for many reasons. You do not owe the app an explanation.',
    'Choose a version you would feel comfortable coming back to, rather than the biggest possible effort.',
    'The plan can grow later if that suits you. There is no need to decide that today.',
    'Coming back can start with opening your plan and choosing one achievable action.',
  ]),
  group('eat-begin', 'eat', 'Make room for a meal', 'nori', [
    'What food is available and practical for you right now? Start with that, rather than an ideal meal.',
    'You can choose something simple. A meal does not have to be a project.',
    'Give yourself a moment to decide what would be satisfying and manageable to eat.',
    'You do not have to earn a meal through exercise or productivity.',
    'If deciding feels difficult, choose a familiar option that fits your needs.',
    'There is room for convenience. Use the food and help that make eating possible today.',
    'You can make a little space for your food, even if the rest of the day feels untidy.',
    'Choose what works with your preferences, access, and dietary needs.',
    'A meal can be ordinary and still deserve your time.',
    'You can leave judgement out of this moment and focus on what is practical to eat.',
  ]),
  group('eat-simple', 'eat', 'When cooking feels like a lot', 'nori', [
    'Think of one familiar meal with fewer steps. That can be your starting point today.',
    'You can use ready-prepared ingredients if they make the meal more manageable.',
    'A simple assembly of foods you enjoy can be enough. It does not need a recipe title.',
    'If cooking is not possible, choose an available option that meets your needs.',
    'You might prepare just the next meal, rather than planning the whole week.',
    'Choose the easiest useful step: find a bowl, take out an ingredient, or decide on a familiar dish.',
    'There is no need to make everything from scratch to take care of yourself.',
    'You can repeat a meal you like. Variety does not need to become pressure at every sitting.',
    'Let the meal fit the energy you have for making it.',
    'If help is available, you can ask for it. Preparing food does not have to be a solo task.',
  ]),
  group('eat-pantry', 'eat', 'Start with what you have', 'momo', [
    'Choose one ingredient you already have and a familiar way you like to use it.',
    'A quick look at your available food can make the next decision smaller.',
    'Check what needs using, and follow the storage and date guidance on the packaging.',
    'You can build your shopping list around a meal you already know you enjoy.',
    'If an ingredient is missing, a familiar suitable alternative may keep the plan simple.',
    'You do not need to use everything at once. Choose what makes sense for the next meal.',
    'Let your budget and available ingredients guide the plan without turning it into a test.',
    'You can keep a short list of meals that work with your usual cupboard staples.',
    'Before shopping, check whether you already have the main thing you need.',
    'If you are unsure whether food is safe to eat, follow trusted food-safety advice rather than guessing.',
  ]),
  group('eat-shopping', 'eat', 'A smaller shopping list', 'momo', [
    'Write down the foods for one or two useful meals first. The list can grow only if it needs to.',
    'Keep familiar, practical options on your list. Shopping does not need to reinvent your routine.',
    'You can group similar items together to make the shop easier to follow.',
    'A short list can hold the remembering for you. Add the things you know you need.',
    'Choose quantities that fit your household, storage space, and plans.',
    'Leave room for your budget. A useful list does not have to be an ambitious one.',
    'If the usual item is unavailable, pause and choose a suitable alternative rather than rushing.',
    'Check ingredients against any allergies or dietary requirements that apply to you.',
    'You can keep a few reliable meal ingredients on the list for busy days.',
    'When the list feels too long, start with the essentials for your next meals.',
  ]),
  group('eat-notice', 'eat', 'A moment with your food', 'nori', [
    'If it feels comfortable, notice one flavour or texture in the food you have chosen.',
    'You do not need to turn eating into an exercise. A small moment of attention is optional.',
    'You can choose a comfortable place to eat, if your day allows it.',
    'Let the meal have a little space in your day without grading it.',
    'If noticing food closely is not helpful for you, you can simply eat in the way that suits you.',
    'There is no perfect pace to match in this recording. Take the time that feels practical.',
    'You can enjoy a familiar food without making it a reward you had to earn.',
    'A meal can include comfort, convenience, culture, and enjoyment. It does not need one single purpose.',
    'You do not need to compare this meal with someone else’s plate.',
    'Let the words finish, and give your attention to whatever makes eating feel manageable today.',
  ]),
  group('eat-log', 'eat', 'Remember without judging', 'nori', [
    'If you want a record, write what you ate in the amount of detail that feels useful.',
    'You can leave numbers out and keep a simple note about your meal.',
    'A food record can help you remember practical things, such as a meal you would like to make again.',
    'You do not need to label the meal good or bad to remember it.',
    'If tracking food feels unhelpful, you can skip the record and keep using the other tools.',
    'You might note what made the meal easier today, rather than giving it a score.',
    'A short description can be enough. The record is for you.',
    'If you are unsure about an amount, avoid treating a guess as an exact measurement.',
    'You can use your history to find meals you enjoyed and practical ideas for later.',
    'Before saving, check that the words say what you want to remember.',
  ]),
  group('focus-start', 'focus', 'One small starting point', 'pip', [
    'Choose one thing you can begin without solving the whole task first.',
    'Make the first step concrete: open the document, find the tool, or write one sentence.',
    'You can start with a rough version. It does not have to look finished yet.',
    'Pick a piece of the task that fits the time and attention you have right now.',
    'If starting feels difficult, make the starting action smaller.',
    'You do not need a perfect plan to take one useful step.',
    'Put one task in front of you, and let the rest stay on the list for now.',
    'Choose what you are beginning, then decide how long you would like to try.',
    'You can begin with preparation if that is the step that helps you move forward.',
    'The next action can be small enough to describe in a few words.',
  ]),
  group('focus-return', 'focus', 'After a distraction', 'pip', [
    'You noticed your attention moved. You can return without telling yourself off.',
    'Find the next small action in your task. Begin there, rather than restarting the whole plan.',
    'A distraction does not erase the work you already did.',
    'If a thought needs remembering, put it on a short later list and return when you are ready.',
    'You can close one unnecessary tab if that makes the next step easier.',
    'Take a moment to remember what you meant to do next. There is no rush.',
    'You do not have to recover every lost minute. Choose what is useful now.',
    'If the task has become unclear, write the next action in plain words.',
    'Returning is part of focusing. You are allowed to do it more than once.',
    'You can choose to continue, take a break, or change the plan. Make that choice deliberately.',
  ]),
  group('focus-priority', 'focus', 'Make the list smaller', 'pip', [
    'Which task would make the next part of your day easier? You can start by choosing just that one.',
    'A list can hold possibilities without asking you to finish them all today.',
    'Choose one priority and give it a clear next action.',
    'You can move a task to another day when that is the practical choice.',
    'Not everything that is written down has the same urgency.',
    'Look for what matters now, then let the rest wait somewhere you can find it.',
    'If the list feels crowded, separate what must happen today from what can be reconsidered.',
    'You can remove a task that no longer serves a purpose.',
    'A useful plan leaves room for real life, including interruptions and rest.',
    'You do not need a long list to make a meaningful choice about today.',
  ]),
  group('focus-finish', 'focus', 'Close a focus session', 'pip', [
    'If you are stopping now, leave yourself a short note about where to pick up next time.',
    'You can recognise the attention you gave, even if the task is not finished.',
    'Give the session an ending by saving your work where appropriate and choosing a pause.',
    'What is the next useful step? A few words can save you some remembering later.',
    'You do not need to keep going just because there is more to do.',
    'If you finished something, take a moment to notice it before adding the next task.',
    'A session can end with progress, a discovery, or a clearer question.',
    'Choose whether to continue later or leave the task for another day.',
    'You can put the work down without making a promise to do more tonight.',
    'Let a small ending be enough: close the file, move the note, or turn away from the desk.',
  ]),
  group('progress-small', 'progress', 'Notice a small win', 'pip', [
    'What is one small thing you would like to acknowledge today? It does not need to impress anyone.',
    'You can notice effort that would never appear on a checklist.',
    'A helpful choice can be quiet: asking for support, eating a meal, or taking a pause.',
    'If something felt a little easier today, you can let yourself notice that.',
    'You do not need a streak to recognise a moment of care.',
    'A small win can be something you chose not to add to an already full day.',
    'You can be pleased with one step without claiming that everything is sorted.',
    'If you would like, keep a sentence about what mattered. A sentence is enough.',
    'Progress can include learning what does not work for you.',
    'Look for something real and specific, however small, that you want to remember.',
  ]),
  group('progress-lookback', 'progress', 'Look back kindly', 'luma', [
    'Your history can show moments, not a verdict on who you are. Read it with some room for context.',
    'Look for a pattern that feels useful, rather than a number to judge yourself by.',
    'An empty day in the record is simply a day without an entry. It is not proof that nothing happened.',
    'You can remember the circumstances around a difficult week as well as the things you recorded.',
    'Notice something you would like to repeat, if anything stands out.',
    'Your records belong to you. You can choose how much of the past to look at today.',
    'A change in routine can tell a story worth understanding, without needing blame.',
    'You might find a small practical idea in an older note that would help now.',
    'Compare your plans with what was possible, not with an imaginary perfect week.',
    'You can close the history whenever you have learned enough for today.',
  ]),
  group('progress-reset', 'progress', 'After a difficult day', 'luma', [
    'One difficult day does not need to decide the next one. Choose what would help you now.',
    'You can begin again without making up for every missed plan.',
    'There is no debt of self-care to repay. Start with one need in front of you.',
    'A smaller plan may fit better tomorrow. You are allowed to adjust it.',
    'You do not need to explain a gap before returning to your tools.',
    'If a goal has become pressure, you can reconsider the goal itself.',
    'You can keep what helped and leave the rest of the plan behind.',
    'A fresh start can happen in the middle of a day, without waiting for Monday.',
    'Choose something manageable enough that it feels like an invitation.',
    'You can be honest about what was hard and still make room for a different next step.',
  ]),
  group('progress-next', 'progress', 'Choose tomorrow’s small step', 'pip', [
    'What is one small thing that would support tomorrow? Choose something practical rather than ambitious.',
    'Make the next step easy to recognise when the time comes.',
    'You can put a reminder somewhere useful without filling the whole day with alerts.',
    'Leave some room in the plan for things you cannot predict.',
    'Choose a time that fits your life, and allow yourself to change it if needed.',
    'A useful plan can include a meal, a break, or a familiar piece of movement.',
    'You can prepare one small thing now and leave the rest for tomorrow.',
    'Decide what enough might look like, so the task does not keep growing.',
    'Your next step does not have to be harder than the last one.',
    'Let tomorrow begin with an invitation you would feel comfortable accepting.',
  ]),
  group('everyday-hello', 'everyday', 'A gentle hello', 'sunny', [
    'Hello from Daywell. Choose a little company, a useful tool, or a quiet moment for yourself.',
    'Welcome in. You do not have to arrive with a plan.',
    'You can start with how today feels, or simply choose something you need.',
    'There is room here for an ordinary day. Pick one small place to begin.',
    'Hello. Your next step can be practical, restful, or still undecided.',
    'You can take a moment before choosing. The tools will wait.',
    'Welcome back to your little corner of Daywell. Choose what is useful today.',
    'You do not have to use every part of the app. One helpful thing is enough.',
    'Let this visit fit the day you are actually having.',
    'Come in at your own pace. There is no routine you need to complete before you belong here.',
  ]),
  group('everyday-morning', 'everyday', 'Start the morning gently', 'sunny', [
    'Before the day gets crowded, choose one thing you would like to make room for.',
    'You can begin the morning with something familiar and practical.',
    'There is no need to design the whole day before taking the first step.',
    'Notice what you need this morning, rather than what a perfect morning is supposed to contain.',
    'A slower start can still be a start. Choose what is possible now.',
    'If the morning has already been busy, you can make a small pause here.',
    'Choose one useful thing for the next hour. The rest can stay undecided for a moment.',
    'You can start with food, a comfortable movement, or checking what is planned.',
    'Today does not need to copy yesterday. Make room for the circumstances you have.',
    'Let the first choice be a kind and practical one.',
  ]),
  group('everyday-lowenergy', 'everyday', 'A lower-energy day', 'luma', [
    'If energy feels limited, choose a smaller version of the plan.',
    'You can keep the essentials and reconsider the extras.',
    'There is no need to make a low-energy day look like a high-energy one.',
    'Choose the next action that asks a little less of you.',
    'You can use a familiar shortcut, ask for help, or take a pause.',
    'An easier meal or a shorter task can be a sensible choice today.',
    'Let your plan respond to your circumstances rather than arguing with them.',
    'You can decide what needs doing and what can wait, one thing at a time.',
    'A day with less energy still deserves comfort and care.',
    'If this is a time to rest, you do not have to turn rest into an achievement.',
  ]),
  group('everyday-choice', 'everyday', 'Too many choices', 'pip', [
    'You can narrow the choice to two practical options, then pick the one that feels easier to begin.',
    'Start by asking what you need most immediately, rather than what would be ideal.',
    'A useful choice does not have to be the best possible choice.',
    'You can choose a familiar option when comparing everything feels like too much.',
    'Let one decision be small enough to make now. The others can wait.',
    'If nothing stands out, a short pause is also an available choice.',
    'You do not have to optimise this moment. Something workable can be enough.',
    'Choose what fits the time you have, and allow the plan to stay simple.',
    'You can change your mind after trying a small first step.',
    'Put aside the options that are not practical today. Work with what remains.',
  ]),
  group('everyday-time', 'everyday', 'A little structure', 'tock', [
    'You can choose a short timer to give an activity a clear beginning and end.',
    'Pick a length that feels manageable. A timer is a tool you can change.',
    'You can pause or end a timer when you need to. The number does not make the decision for you.',
    'Decide what the timer is for before you start it: focus, a break, or a familiar activity.',
    'A small amount of time can have a clear purpose without becoming a challenge.',
    'If timing adds pressure today, you can do the activity without a countdown.',
    'Keep the next stretch of time simple enough to explain in one sentence.',
    'You can leave a little space between activities rather than filling every minute.',
    'Choose a stopping point that makes it easier to return later.',
    'Time can help hold a plan, but you are allowed to adjust the plan.',
  ]),
  group('everyday-water', 'everyday', 'A practical check-in', 'sunny', [
    'Would a drink be useful right now? Choose what suits you and any guidance you follow.',
    'Take a moment to check a practical need: a drink, a meal, a comfortable seat, or a break.',
    'You can put something you often need within easy reach.',
    'Before the next task, ask whether there is a small comfort you have been putting off.',
    'If you need to refill your usual drink, this can be a convenient moment.',
    'A practical check-in does not need a score. Notice what would help and choose one thing.',
    'You can take care of an ordinary need before getting back to the list.',
    'Maybe the next useful step is simply making yourself more comfortable.',
    'Choose what your situation calls for, rather than following every suggestion in the app.',
    'You can skip this reminder if it is not useful. Your own needs come first.',
  ]),
  group('everyday-transition', 'everyday', 'Between parts of the day', 'pip', [
    'Let one part of the day end before you ask yourself to begin the next.',
    'You can mark the change with something small, such as putting a tool away or moving to another seat.',
    'What belongs in the next part of your day? Choose one thing to carry forward.',
    'You do not have to take the pace of work into your rest time.',
    'Give yourself a moment to arrive at the next activity.',
    'If a task is unfinished, a short note can make it easier to leave for now.',
    'You can choose a different rhythm for the next hour.',
    'Let the transition include a little space for what you need.',
    'There is no rule that the next activity has to start immediately.',
    'You can begin the next part of the day with one clear, manageable choice.',
  ]),
  group('everyday-kindness', 'everyday', 'A kinder inner voice', 'luma', [
    'Try describing the situation without adding an insult about yourself.',
    'You can name a difficulty and still speak to yourself with care.',
    'A mistake can be something to respond to, rather than a definition of who you are.',
    'You do not need to be harsh with yourself to choose a useful next step.',
    'What would a practical, kind response sound like in this moment?',
    'You can acknowledge that something is hard without deciding you should find it easy.',
    'Let the next sentence you say to yourself leave room for your circumstances.',
    'You are allowed to need support while working on something that matters.',
    'Try replacing a verdict with a description of what happened and what might help next.',
    'Kindness can be ordinary and specific. It does not need to sound like a grand affirmation.',
  ]),
  group('everyday-boundary', 'everyday', 'Leave room in the day', 'pip', [
    'You can check the space in your day before agreeing to another task.',
    'A useful answer can be that you need time to think about it.',
    'You do not have to fill every available gap with something productive.',
    'Choose what fits your responsibilities and the capacity you have today.',
    'You can make a request smaller or ask when it really needs to happen.',
    'A little room in the plan can help you respond when life changes it.',
    'You can leave one part of the day without a new commitment.',
    'Before adding more, look at what you have already chosen to carry.',
    'You are allowed to reconsider a plan when your circumstances change.',
    'Keep some space for ordinary needs, including food, rest, and the unexpected.',
  ]),
  group('everyday-goodbye', 'everyday', 'Take the next step', 'sunny', [
    'You can leave the app and take one small idea with you.',
    'There is nothing else you need to complete here before returning to your day.',
    'Choose the next useful thing, or choose a little more quiet.',
    'Daywell can be a brief visit. You do not need to stay on the screen.',
    'Let the words end and your own day continue at your pace.',
    'You can come back when you want a tool or a little company.',
    'Take what was useful from this moment and leave the rest.',
    'You do not need to turn this visit into a streak. A useful moment is enough.',
    'The next step belongs to you. Keep it manageable.',
    'A little space, a little care, and then back to whatever you choose next.',
  ]),
];

export const audioResponses = audioGroups.flatMap(item => item.responses);
export const audioResponseById = new Map(audioResponses.map(item => [item.id, item]));
export function searchAudioResponses(query: string, category?: AudioCategory): AudioResponse[] {
  const terms = query.toLocaleLowerCase('en-GB').trim().split(/\s+/).filter(Boolean);
  return audioResponses.filter(item => (!category || item.category === category) && terms.every(term => `${item.title} ${item.text}`.toLocaleLowerCase('en-GB').includes(term)));
}
export function responseInGroup(id: string, variation = 0): AudioResponse | undefined {
  const selected = audioGroups.find(item => item.id === id);
  if (!selected) return undefined;
  const index = Number.isFinite(variation) ? Math.max(0, Math.floor(variation)) % selected.responses.length : 0;
  return selected.responses[index];
}
export type AudioRecording = { src: string; text: string; bytes: number };
export type AudioManifest = { version: 1; recordings: Record<string, AudioRecording> };
export function recordingFor(response: AudioResponse, manifest: AudioManifest | null): AudioRecording | undefined {
  const item = manifest?.recordings?.[response.id];
  // A changed script must never silently play an old recording or a remote URL.
  return item && item.text === response.text && /^\/audio-library\/[a-z0-9-]+\.mp3$/.test(item.src) && item.bytes > 1000 ? item : undefined;
}
