import {z} from "zod";
import {schemas,sleepMinutes,type Entry} from "./daywell.ts";
import {actionSchema} from "./food.ts";
import {intakeRecord,intakeSchema} from "./food-tracking.ts";
const nullableString={type:["string","null"]},nullableNumber={type:["number","null"]};
const properties={kind:{type:"string",enum:["task","grocery","food","sleep","move","alarm","timer","stock"]},title:{type:"string"},date:nullableString,minutes:nullableNumber,time:nullableString,endTime:nullableString,quantity:nullableString,calories:nullableNumber,protein:nullableNumber,carbs:nullableNumber,fat:nullableNumber,meal:{type:["string","null"],enum:["Breakfast","Lunch","Dinner","Snack",null]},quality:{type:["string","null"],enum:["Rested","Okay","Tired",null]},repeatDays:{type:"array",items:{type:"integer"}},portions:nullableNumber,sugarGrams:nullableNumber,sugarSource:{type:["string","null"],enum:["label","user",null]},stockQuantity:nullableNumber,stockUnit:{type:["string","null"],enum:["g","kg","ml","l","each","portion",null]}};
export const captureJsonSchema={type:"object",additionalProperties:false,properties:{summary:{type:"string"},question:{type:["string","null"]},actions:{type:"array",items:{type:"object",additionalProperties:false,properties,required:Object.keys(properties)}}},required:["summary","question","actions"]};
export const captureSchema=z.object({summary:z.string().max(800),question:z.string().max(500).nullable(),actions:z.array(z.object({kind:z.enum(["task","grocery","food","sleep","move","alarm","timer","stock"]),title:z.string().max(160),date:z.string().nullable(),minutes:z.number().nullable(),time:z.string().nullable(),endTime:z.string().nullable(),quantity:z.string().nullable(),calories:z.number().nullable(),protein:z.number().nullable(),carbs:z.number().nullable(),fat:z.number().nullable(),meal:z.enum(["Breakfast","Lunch","Dinner","Snack"]).nullable(),quality:z.enum(["Rested","Okay","Tired"]).nullable(),repeatDays:z.array(z.number().int().min(0).max(6)),portions:z.number().nullable().optional(),sugarGrams:z.number().nullable().optional(),sugarSource:z.enum(["label","user"]).nullable().optional(),stockQuantity:z.number().nullable().optional(),stockUnit:z.enum(["g","kg","ml","l","each","portion"]).nullable().optional()})).max(20)});
export function draftEntries(value:unknown,date:string,enabled:string[],mode="auto"){const parsed=captureSchema.parse(value);if(parsed.question)return {summary:parsed.summary,question:parsed.question,entries:[],basket:[]};
const expected:Record<string,string>={meal:"food",basket:"stock",grocery:"grocery"};
if(expected[mode]&&parsed.actions.some(x=>x.kind!==expected[mode]))throw Error("Please keep this capture to the selected food task.");
const stock=parsed.actions.filter(x=>x.kind==="stock");
if(stock.length&&!enabled.includes("food"))throw Error("Enable food to use your basket.");
if(stock.some(x=>x.stockQuantity!=null&&!x.stockUnit))throw Error("Please confirm the unit for that basket amount.");
if(mode==="auto"&&stock.length)throw Error("Choose Food basket before adding inventory.");
const basket=stock.map(x=>actionSchema.parse({type:"stock.set",item:{id:crypto.randomUUID(),ingredient:x.title,quantity:x.stockQuantity??null,unit:x.stockUnit??"each",bestBefore:null}})).map(x=>{if(x.type!=="stock.set")throw Error("Invalid basket draft");return x.item;});
const map:Record<string,string>={task:"focus",grocery:"grocery",food:"food",sleep:"sleep",move:"move",alarm:"alarm",timer:"clock"};const entries:Entry[]=parsed.actions.filter(x=>x.kind!=="stock").map(action=>{const x=action;if(x.kind==="stock")throw Error("Use the basket review for inventory.");if(!enabled.includes(map[x.kind])&&!(x.kind==="timer"&&enabled.includes("focus")))throw Error(`Enable ${map[x.kind]} to use this tool.`);let data:any;
 switch(x.kind){case "task":data={title:x.title,date:x.date||date,minutes:x.minutes??25,done:false};break;case "grocery":data={title:x.title,quantity:x.quantity||"1",done:false};break;case "food": { const intake=intakeSchema.parse({portions:x.portions??1,calories:x.calories??undefined,macros:[x.protein,x.carbs,x.fat].every(v=>v!==null)?{protein:x.protein,carbs:x.carbs,fat:x.fat}:undefined,sugarGrams:x.sugarSource?x.sugarGrams??undefined:undefined,source:"estimate"});data={title:x.title,date:x.date||date,meal:x.meal||"Snack",...intakeRecord(intake,"prepared")};break;}case "sleep":if(!x.time||!x.endTime)throw Error("Please include both your bedtime and wake time.");data={date:x.date||date,bedtime:x.time,wakeTime:x.endTime,minutes:sleepMinutes(x.time,x.endTime),quality:x.quality||"Okay"};break;case "move":data={title:x.title,date:x.date||date,minutes:x.minutes};break;case "alarm":if(x.date&&x.date!==date&&!x.repeatDays.length)throw Error("Date-specific alarms are not available yet. Please use a repeating alarm or your phone for that date.");data={title:x.title||"Alarm",time:x.time,days:x.repeatDays,enabled:true};break;case "timer":data={title:x.title||"Your timer",duration:(x.minutes||0)*60,remaining:(x.minutes||0)*60,endAt:null,mode:"Timer"};break;}
 return {id:x.kind==="timer"?"timer":crypto.randomUUID(),kind:x.kind,data:schemas[x.kind].parse(data)};});if(entries.filter(e=>e.kind==="timer").length>1)throw Error("Please start one timer at a time.");return {summary:parsed.summary,question:null,entries,basket};}
